import type { Formula } from "@/engine/types";

export const FORMULAS: Formula[] = [
  {
    id: "mru",
    name: "Posición en el MRU",
    expression: "x(t) = x₀ + v·t",
    subjectId: "fisica",
    meaning: "Dónde está un móvil que se mueve en línea recta a velocidad constante.",
    whenToUse: "Cuando la velocidad NO cambia (aceleración cero).",
    variables: [
      { symbol: "x(t)", meaning: "posición en el instante t", unit: "m" },
      { symbol: "x₀", meaning: "posición inicial (en t = 0)", unit: "m" },
      { symbol: "v", meaning: "velocidad (con signo)", unit: "m/s" },
      { symbol: "t", meaning: "tiempo transcurrido", unit: "s" },
    ],
    example: "x₀ = 10 m, v = 3 m/s, t = 4 s → x = 10 + 12 = 22 m",
    commonErrors: ["Olvidar sumar la posición inicial x₀.", "Usar km/h junto con segundos sin convertir.", "Pensar que v negativa significa «frenar»: significa ir en sentido negativo."],
    tags: ["cinemática", "movimiento", "velocidad constante"],
  },
  {
    id: "mruv-velocidad",
    name: "Velocidad en el MRUV",
    expression: "v(t) = v₀ + a·t",
    subjectId: "fisica",
    meaning: "Cómo cambia la velocidad cuando la aceleración es constante.",
    whenToUse: "Movimientos con aceleración constante: arranques, frenadas, caída libre, tiro vertical.",
    variables: [
      { symbol: "v(t)", meaning: "velocidad en el instante t", unit: "m/s" },
      { symbol: "v₀", meaning: "velocidad inicial", unit: "m/s" },
      { symbol: "a", meaning: "aceleración", unit: "m/s²" },
      { symbol: "t", meaning: "tiempo", unit: "s" },
    ],
    example: "v₀ = 4 m/s, a = 2 m/s², t = 3 s → v = 4 + 6 = 10 m/s",
    commonErrors: ["Confundir velocidad con aceleración.", "Olvidar que a puede ser negativa (frenado o gravedad con eje hacia arriba)."],
    tags: ["cinemática", "aceleración"],
  },
  {
    id: "mruv-posicion",
    name: "Posición en el MRUV",
    expression: "x(t) = x₀ + v₀·t + ½·a·t²",
    subjectId: "fisica",
    meaning: "Dónde está un móvil con aceleración constante.",
    whenToUse: "Cuando necesitás la posición y la aceleración es constante.",
    variables: [
      { symbol: "x₀", meaning: "posición inicial", unit: "m" },
      { symbol: "v₀", meaning: "velocidad inicial", unit: "m/s" },
      { symbol: "a", meaning: "aceleración", unit: "m/s²" },
      { symbol: "t", meaning: "tiempo", unit: "s" },
    ],
    example: "x₀ = 0, v₀ = 0, a = 2 m/s², t = 5 s → x = ½·2·25 = 25 m",
    commonErrors: ["Olvidar el ½.", "Escribir a·t en lugar de a·t².", "Usarla con aceleración variable."],
    tags: ["cinemática", "aceleración", "parábola"],
  },
  {
    id: "caida-libre",
    name: "Caída libre",
    expression: "y(t) = y₀ + v₀·t − ½·g·t²",
    subjectId: "fisica",
    meaning: "MRUV vertical con la aceleración de la gravedad, tomando el eje y hacia arriba.",
    whenToUse: "Objetos que caen o se lanzan verticalmente, despreciando el aire.",
    variables: [
      { symbol: "y₀", meaning: "altura inicial", unit: "m" },
      { symbol: "v₀", meaning: "velocidad inicial (positiva si va hacia arriba)", unit: "m/s" },
      { symbol: "g", meaning: "aceleración de la gravedad ≈ 9,8", unit: "m/s²" },
    ],
    example: "Se suelta desde 20 m: 0 = 20 − 4,9·t² → t ≈ 2,02 s",
    commonErrors: ["Usar +g con el eje hacia arriba.", "Pensar que la aceleración es 0 en la altura máxima (es la velocidad la que vale 0)."],
    tags: ["cinemática", "gravedad", "tiro vertical"],
  },
  {
    id: "altura-maxima",
    name: "Altura máxima (tiro vertical)",
    expression: "h_máx = v₀² / (2g)",
    subjectId: "fisica",
    meaning: "Cuánto sube un objeto lanzado verticalmente hacia arriba con velocidad v₀.",
    whenToUse: "Tiro vertical desde el suelo, sin rozamiento.",
    variables: [
      { symbol: "v₀", meaning: "velocidad de lanzamiento", unit: "m/s" },
      { symbol: "g", meaning: "gravedad ≈ 9,8", unit: "m/s²" },
    ],
    example: "v₀ = 19,6 m/s → h = 384,16/19,6 = 19,6 m",
    commonErrors: ["Olvidar el 2 del denominador.", "Aplicarla cuando el lanzamiento no es vertical."],
    tags: ["tiro vertical"],
  },
  {
    id: "modulo-vector",
    name: "Módulo de un vector",
    expression: "|v| = √(x² + y²)",
    subjectId: "fisica",
    meaning: "El largo de la flecha que representa al vector.",
    whenToUse: "Cuando conocés las componentes y necesitás la magnitud (rapidez, intensidad de una fuerza…).",
    variables: [
      { symbol: "x", meaning: "componente horizontal" },
      { symbol: "y", meaning: "componente vertical" },
    ],
    example: "v = (6, 8) → |v| = √(36 + 64) = 10",
    commonErrors: ["Sumar las componentes en vez de usar Pitágoras.", "Olvidar la raíz.", "Pensar que el módulo puede ser negativo."],
    tags: ["vectores", "pitágoras", "norma"],
  },
  {
    id: "componentes-vector",
    name: "Componentes de un vector",
    expression: "vₓ = |v|·cos θ   ·   v_y = |v|·sen θ",
    subjectId: "fisica",
    meaning: "Descompone un vector en sus partes horizontal y vertical.",
    whenToUse: "Cuando conocés el módulo y el ángulo medido desde el eje x positivo.",
    variables: [
      { symbol: "|v|", meaning: "módulo del vector" },
      { symbol: "θ", meaning: "ángulo desde el eje x positivo", unit: "°" },
    ],
    example: "|v| = 10, θ = 30° → vₓ ≈ 8,66, v_y = 5",
    commonErrors: ["Intercambiar seno y coseno.", "Calculadora en radianes cuando el ángulo está en grados."],
    tags: ["vectores", "trigonometría"],
  },
  {
    id: "producto-escalar",
    name: "Producto escalar",
    expression: "u·v = u₁v₁ + u₂v₂ (+ u₃v₃)",
    subjectId: "algebra-a",
    meaning: "Combina dos vectores en un número que refleja el ángulo entre ellos: u·v = |u||v|cos θ.",
    whenToUse: "Para calcular ángulos entre vectores, verificar perpendicularidad o proyectar.",
    variables: [{ symbol: "uᵢ, vᵢ", meaning: "componentes de cada vector" }],
    example: "(1, 2)·(3, −1) = 3 − 2 = 1",
    commonErrors: ["Multiplicar componentes cruzadas.", "Dar como resultado un vector."],
    tags: ["vectores", "ortogonalidad", "ángulo"],
  },
  {
    id: "pendiente",
    name: "Pendiente de una recta",
    expression: "m = (y₂ − y₁) / (x₂ − x₁)",
    subjectId: "am-a",
    meaning: "Cuánto sube (o baja) la recta por cada unidad que avanza en x.",
    whenToUse: "Cuando conocés dos puntos de una recta, o para interpretar una tasa de cambio.",
    variables: [
      { symbol: "(x₁, y₁)", meaning: "primer punto" },
      { symbol: "(x₂, y₂)", meaning: "segundo punto" },
    ],
    example: "(1, 2) y (3, 8) → m = 6/2 = 3",
    commonErrors: ["Invertir: Δx/Δy.", "Restar en distinto orden arriba y abajo."],
    tags: ["función lineal", "recta", "tasa de cambio"],
  },
  {
    id: "recta",
    name: "Función lineal",
    expression: "y = m·x + b",
    subjectId: "am-a",
    meaning: "Recta de pendiente m que corta al eje y en b.",
    whenToUse: "Modelar algo que cambia a ritmo constante.",
    variables: [
      { symbol: "m", meaning: "pendiente" },
      { symbol: "b", meaning: "ordenada al origen" },
    ],
    example: "y = 2x − 1 pasa por (0, −1) y (1, 1)",
    commonErrors: ["Confundir m con b cuando la fórmula está escrita en otro orden (y = 3 + 2x → m = 2)."],
    tags: ["función lineal", "recta"],
  },
  {
    id: "porcentaje",
    name: "Porcentaje",
    expression: "p% de N = (p/100)·N",
    subjectId: "preparacion",
    meaning: "Qué parte de N representa p de cada 100.",
    whenToUse: "Descuentos, aumentos, impuestos, eficiencias, errores relativos.",
    variables: [
      { symbol: "p", meaning: "porcentaje" },
      { symbol: "N", meaning: "cantidad total" },
    ],
    example: "15% de 200 = 0,15·200 = 30",
    commonErrors: ["Olvidar dividir por 100.", "Sumar el porcentaje como si fueran unidades."],
    tags: ["proporciones"],
  },
  {
    id: "distributiva",
    name: "Propiedad distributiva",
    expression: "a·(b + c) = a·b + a·c",
    subjectId: "preparacion",
    meaning: "El factor de afuera multiplica a cada término de adentro.",
    whenToUse: "Para sacar paréntesis o, al revés, para sacar factor común.",
    variables: [],
    example: "3(x − 2) = 3x − 6",
    commonErrors: ["Multiplicar solo el primer término: 3(x − 2) ≠ 3x − 2.", "Distribuir una potencia: (a + b)² ≠ a² + b²."],
    tags: ["álgebra"],
  },
  {
    id: "potencias",
    name: "Propiedades de las potencias",
    expression: "aᵐ·aⁿ = aᵐ⁺ⁿ   ·   aᵐ/aⁿ = aᵐ⁻ⁿ   ·   (aᵐ)ⁿ = aᵐ·ⁿ",
    subjectId: "preparacion",
    meaning: "Reglas para operar potencias de igual base.",
    whenToUse: "Simplificar expresiones, notación científica, unidades.",
    variables: [],
    example: "2³·2⁴ = 2⁷ = 128",
    commonErrors: ["Multiplicar exponentes en un producto (2³·2⁴ ≠ 2¹²).", "Aplicarlas con bases distintas."],
    tags: ["potencias", "exponentes"],
  },
  {
    id: "velocidad-conversion",
    name: "Conversión km/h ↔ m/s",
    expression: "v[m/s] = v[km/h] / 3,6",
    subjectId: "fisica",
    meaning: "1 km/h = 1000 m / 3600 s = 1/3,6 m/s.",
    whenToUse: "Antes de usar velocidades en km/h en fórmulas con segundos.",
    variables: [],
    example: "108 km/h / 3,6 = 30 m/s",
    commonErrors: ["Multiplicar en lugar de dividir (m/s siempre da un número más chico que km/h)."],
    tags: ["unidades", "conversión"],
  },
  {
    id: "presion",
    name: "Presión",
    expression: "P = F / A",
    subjectId: "fisica",
    meaning: "Fuerza repartida por unidad de área.",
    whenToUse: "Hidrostática y cualquier fuerza distribuida sobre una superficie.",
    variables: [
      { symbol: "P", meaning: "presión", unit: "Pa = N/m²" },
      { symbol: "F", meaning: "fuerza perpendicular a la superficie", unit: "N" },
      { symbol: "A", meaning: "área", unit: "m²" },
    ],
    example: "F = 100 N sobre A = 0,5 m² → P = 200 Pa",
    commonErrors: ["Usar el área en cm² sin pasar a m²."],
    tags: ["hidrostática"],
  },
];

export function getFormula(id: string): Formula | undefined {
  return FORMULAS.find((f) => f.id === id);
}
