import type { Lesson } from "@/engine/types";
import { board, example, explain, intro, practice, quiz, row, summary } from "./helpers";

export const unidades: Lesson = {
  id: "l-unidades",
  title: "Unidades y notación científica",
  subtitle: "Medir y convertir sin perderse",
  subjectId: "fisica",
  topicIds: ["t-unidades"],
  estimatedMinutes: 12,
  prerequisites: ["t-potencias"],
  cards: [
    intro("Unidades", "El Sistema Internacional, cómo convertir unidades y cómo escribir números muy grandes o muy chicos.", "En Física, un resultado sin unidad está incompleto y una unidad mal convertida arruina todo el ejercicio. Es uno de los errores más frecuentes del CBC."),
    explain(
      "Un número no alcanza",
      "«La distancia es 5» no dice nada. ¿5 metros? ¿5 kilómetros? Una **magnitud física** es número + unidad.\n\nEl **Sistema Internacional (SI)** usa: metro (m) para longitud, segundo (s) para tiempo, kilogramo (kg) para masa. Las demás se arman con estas: velocidad en m/s, aceleración en m/s².",
      { tag: "intuitivo" },
    ),
    quiz("Pregunta rápida", {
      id: "q3-uni-si",
      subjectId: "fisica",
      topicId: "t-unidades",
      prompt: "¿Cuál es la unidad de velocidad en el Sistema Internacional?",
      options: ["m/s", "km/h", "m/s²"],
      answer: 0,
      explanation: "En el SI la longitud va en metros y el tiempo en segundos: la velocidad, en m/s. Los km/h son muy usados, pero no son SI.",
      hints: ["El SI usa metro y segundo.", "Velocidad = distancia / tiempo.", "metros / segundos."],
      errors: { 1: ["unidades", "km/h es habitual en la vida diaria, pero no es la unidad SI. Hay que pasarla a m/s."], 2: ["unidades", "m/s² es la unidad de aceleración (cuánto cambia la velocidad por segundo)."] },
    }),
    explain(
      "Convertir = multiplicar por 1",
      "Como 1 km = 1000 m, la fracción (1000 m)/(1 km) vale 1. Multiplicar por 1 no cambia la cantidad, pero cambia la unidad:\n\n3 km · (1000 m)/(1 km) = 3000 m\n\nLos «km» se cancelan como en una fracción.",
      { tag: "matematico" },
    ),
    board(
      "Pizarra: convertir con factores",
      [
        row("108 km/h"),
        row("108 km/h · (1000 m)/(1 km)", "factor que vale 1: 1 km son 1000 m"),
        row("108 000 m/h", "se cancelan los km"),
        row("108 000 m/h · (1 h)/(3600 s)", "otro factor que vale 1: 1 h son 3600 s"),
        row("30 m/s", "se cancelan las horas: $108 000 ÷ 3600 = 30$"),
      ],
      "Pasemos 108 km/h a m/s sin atajos:",
      "Control con el atajo: $108 ÷ 3,6 = 30$ ✓.",
    ),
    explain(
      "km/h ↔ m/s",
      "$72$ km/h $= 72 · 1000$ m $/ 3600$ s $= 20$ m/s.\n\nComo $1000/3600 = 1/3,6$: de km/h a m/s se **divide por 3,6**; de m/s a km/h se **multiplica por 3,6**.\n\nControl de sentido común: m/s siempre da un número más chico que km/h.",
      { widget: { type: "units", value: 72 }, tag: "cotidiano" },
    ),
    example("Ejemplo resuelto", "Pasá 90 km/h a m/s", ["$90 · 1000 = 90 000$ m", "1 h $= 3600$ s", "$90 000 / 3600 = 25$ m/s", "Atajo: $90 / 3,6 = 25$ ✓"], "25 m/s"),
    practice("Ejercicio guiado", "conversion-unidades", 2, 3, true),
    practice("Tu turno", "conversion-unidades", 3, 11),
    explain(
      "Notación científica",
      "La distancia Tierra–Sol es unos $150 000 000 000$ m. Más cómodo: $1,5 × 10^{11}$ m.\n\nForma: $a × 10^n$ con $1 ≤ a < 10$. Números grandes → $n$ positivo. Números chicos → $n$ negativo: $0,0003 = 3 × 10^{−4}$.",
      { tag: "matematico" },
    ),
    practice("Tu turno", "notacion-cientifica", 3, 5),
    practice("Mini desafío", "conversion-unidades", 4, 19),
    summary(["Magnitud = número + unidad.", "Convertir es multiplicar por fracciones que valen 1.", "km/h → m/s: ÷ 3,6. m/s → km/h: · 3,6.", "Notación científica: a × 10ⁿ con 1 ≤ a < 10."]),
  ],
  tutor: {
    normal: "Toda magnitud física se expresa como valor numérico y unidad. Para convertir se multiplica por factores de conversión iguales a 1, de modo que las unidades no deseadas se cancelen.",
    simple: "Para pasar a una unidad más chica, el número crece (2 km = 2000 m). Para pasar a una más grande, el número se achica (500 g = 0,5 kg).",
    nino: "Es como cambiar plata: 100 dólares y su equivalente en pesos son la misma riqueza escrita con distinta unidad. Para pasar de una a otra multiplicás por la cotización, que es justamente un factor de conversión. Con las unidades físicas pasa lo mismo, pero la «cotización» no cambia nunca: 1 km siempre son 1000 m.",
    ejemplo: "54 km/h = 15 m/s (54 ÷ 3,6). 2,5 h = 150 min = 9000 s. 0,000 25 m = 2,5 × 10⁻⁴ m.",
    visual: { type: "units", value: 36 },
    visualText: "Escribí una velocidad en km/h y mirá su equivalente en m/s: siempre es 3,6 veces más chico.",
    fromZero: "Medir es comparar con un patrón. Decir «la mesa mide 2 metros» significa que el metro patrón entra dos veces en la mesa. Por eso un número solo no alcanza: hay que decir **con qué patrón** se comparó (la unidad). La misma mesa mide 200 centímetros: cambia el número porque cambió el patrón, no la mesa. Convertir es pasar de un patrón a otro: si cada metro tiene 100 cm, el número en centímetros es 100 veces mayor. La notación científica es otra comodidad: escribir $3 × 10^5$ en lugar de $300 000$, contando los ceros con el exponente.",
    why: "Porque en Física las fórmulas solo funcionan si todas las magnitudes están en unidades compatibles: mezclar km/h con segundos da resultados absurdos. Además, controlar las unidades al final de una cuenta es una forma rápida de detectar errores: si buscabas un tiempo y te quedó en m/s, algo se despejó mal.",
    origin: "Los factores de conversión salen de una equivalencia: como 1 km = 1000 m, el cociente (1000 m)/(1 km) vale exactamente 1. Multiplicar por 1 no cambia la cantidad, solo cómo está escrita. El 3,6 del atajo sale de combinar dos factores: 1 km/h = 1000 m / 3600 s = 1/3,6 m/s.",
    board: [
      { expr: "(3 × 10^5)·(2 × 10^{−2})" },
      { expr: "(3·2) × 10^{5 + (−2)}", note: "se multiplican los números y se suman los exponentes" },
      { expr: "6 × 10^3" },
      { expr: "6000", note: "control: $300 000 · 0,02 = 6000$ ✓" },
    ],
  },
};

export const vectores: Lesson = {
  id: "l-vectores",
  title: "Vectores",
  subtitle: "Flechas con dirección",
  subjectId: "fisica",
  topicIds: ["t-vectores"],
  estimatedMinutes: 12,
  prerequisites: ["t-potencias", "t-signos"],
  cards: [
    intro("Vectores", "Qué es un vector, sus componentes, cómo calcular su módulo y cómo sumarlos.", "Velocidad, aceleración y fuerza son vectores. La Unidad 1 de Física y la Unidad 1 de Álgebra A empiezan exactamente acá."),
    explain(
      "No alcanza con «cuánto»",
      "Si te digo «caminá 5 cuadras», no sabés a dónde llegás. Hace falta **hacia dónde**.\n\nUn **vector** tiene módulo (cuánto) y dirección y sentido (hacia dónde). Se dibuja como una flecha. La temperatura, en cambio, es un **escalar**: solo un número.",
      { tag: "cotidiano" },
    ),
    quiz("Pregunta rápida", {
      id: "q3-vec-tipo",
      subjectId: "fisica",
      topicId: "t-vectores",
      prompt: "¿Cuál de estas magnitudes es un vector?",
      options: ["Una fuerza de 10 N hacia abajo", "Una masa de 3 kg", "Una temperatura de 25 °C"],
      answer: 0,
      explanation: "La fuerza necesita módulo (10 N) y dirección y sentido (hacia abajo). La masa y la temperatura quedan descriptas con un solo número: son escalares.",
      hints: ["¿Cuál necesita decir «hacia dónde»?", "Empujar hacia arriba o hacia abajo no es lo mismo.", "La fuerza."],
      errors: { 1: ["vectores", "La masa no tiene dirección: 3 kg son 3 kg en cualquier orientación. Es un escalar."], 2: ["vectores", "La temperatura es solo un número: es un escalar."] },
    }),
    explain(
      "Componentes",
      "En el plano, una flecha se describe con dos números: cuánto avanza en $x$ y cuánto en $y$. Se escribe $v = (3, 4)$.\n\nArrastrá la punta del vector y mirá cómo cambian sus componentes y su módulo:",
      { widget: { type: "vector", x: 3, y: 4 }, tag: "intuitivo" },
    ),
    quiz("Pregunta rápida", {
      id: "q3-vec-comp",
      subjectId: "fisica",
      topicId: "t-vectores",
      prompt: "El vector $v = (−2, 5)$, ¿hacia dónde apunta?",
      options: ["2 hacia la izquierda y 5 hacia arriba", "2 hacia la derecha y 5 hacia abajo", "5 hacia la izquierda y 2 hacia arriba"],
      answer: 0,
      explanation: "La primera componente es x (−2: hacia la izquierda) y la segunda es y (5: hacia arriba).",
      hints: ["El orden es (x, y).", "x negativo: hacia la izquierda.", "y positivo: hacia arriba."],
      errors: { 1: ["signos", "Invertiste los signos: −2 en x es hacia la izquierda y +5 en y es hacia arriba."], 2: ["vectores", "Intercambiaste las componentes: primero va x, después y."] },
    }),
    explain(
      "Módulo: Pitágoras",
      "Las componentes y la flecha forman un triángulo rectángulo. El largo de la flecha es la hipotenusa:\n\n$|v| = √(x^2 + y^2)$\n\nPara $(3, 4)$: $√(9 + 16) = √25 = 5$. El módulo siempre es positivo (es un largo).",
      { tag: "matematico" },
    ),
    board(
      "Pizarra: calcular un módulo",
      [
        row("v = (5, −12)"),
        row("|v| = √(5^2 + (−12)^2)", "Pitágoras con las componentes"),
        row("|v| = √(25 + 144)", "el cuadrado de un negativo es positivo"),
        row("|v| = √169"),
        row("|v| = 13", "un largo: siempre positivo"),
      ],
    ),
    example("Ejemplo resuelto", "Módulo de $v = (−6, 8)$", ["$|v| = √((−6)^2 + 8^2)$", "$= √(36 + 64)$", "$= √100 = 10$"], "10"),
    practice("Ejercicio guiado", "vector-modulo", 2, 4, true),
    practice("Tu turno", "vector-modulo", 4, 12),
    explain(
      "Sumar vectores",
      "Se suma **componente a componente**: $(1, 3) + (4, −1) = (5, 2)$.\n\nGeométricamente: ponés una flecha a continuación de la otra; la suma va del inicio de la primera a la punta de la segunda.",
      { widget: { type: "vector", x: 4, y: -1, showSum: true }, tag: "intuitivo" },
    ),
    practice("Tu turno", "vector-suma", 2, 8),
    explain(
      "Componentes desde un ángulo",
      "Si conocés el módulo $|v|$ y el ángulo $θ$ con el eje $x$:\n\n$v_x = |v|·cos(θ)$ · $v_y = |v|·sen(θ)$\n\nCoseno va con el cateto **adyacente** al ángulo (el eje x), seno con el **opuesto**. Tocá ▶ para ver cómo se proyecta:",
      { tag: "matematico", widget: { type: "vector-components", mag: 6, angle: 30 } },
    ),
    practice("Tu turno", "vector-componentes", 3, 6),
    practice("Mini desafío", "vector-suma", 5, 16),
    summary(["Vector = módulo + dirección + sentido.", "v = (x, y): componentes.", "|v| = √(x² + y²).", "Suma: componente a componente.", "vx = |v|cos θ, vy = |v|sen θ."]),
  ],
  tutor: {
    normal: "Un vector es una magnitud con módulo, dirección y sentido. En el plano se representa por sus componentes (x, y); su módulo es √(x² + y²) y se suma componente a componente.",
    simple: "Un vector es una flecha. (3, 4) significa «3 a la derecha y 4 para arriba». Su largo se calcula con Pitágoras.",
    nino: "Indicaciones en una ciudad cuadriculada: «3 cuadras al este y 4 al norte». Esas son las componentes. Si pudieras cruzar en diagonal por un parque, recorrerías 5 cuadras en línea recta: ese es el módulo. Y si después alguien te dice «ahora 1 al este y 2 al sur», sumás cuadras por separado en cada dirección.",
    ejemplo: "u = (6, −1) y w = (−2, 4): u + w = (4, 3), y |u + w| = √(16 + 9) = 5. Ojo: |u| + |w| ≈ 6,08 + 4,47 = 10,55, que no es 5: los módulos no se suman directamente.",
    visual: { type: "vector", x: 3, y: 4 },
    visualText: "Arrastrá la punta: el módulo se recalcula solo.",
    fromZero: "Hay cantidades que quedan dichas con un número: 3 kg, 25 °C. Otras necesitan además una dirección: si alguien empuja un carrito con 10 N, importa hacia dónde. Esas cantidades se representan con **flechas**, llamadas vectores. El largo de la flecha es el **módulo** (cuánto); hacia dónde apunta, la dirección y el sentido. En un plano con ejes, cualquier flecha que sale del origen se puede describir diciendo cuánto avanza en horizontal y cuánto en vertical: $(3, 4)$ es «3 a la derecha y 4 hacia arriba». Esos dos números son las **componentes**, y con ellas se hacen todas las cuentas.",
    why: "Porque la Física trabaja con fuerzas, velocidades y aceleraciones, y todas tienen dirección. Descomponerlas en componentes convierte un problema en el plano en dos problemas en línea recta, mucho más fáciles: lo horizontal por un lado, lo vertical por otro. Es lo que vas a hacer en tiro oblicuo, planos inclinados y equilibrio de fuerzas.",
    origin: "El módulo sale de Pitágoras: las componentes $x$ e $y$ son los catetos de un triángulo rectángulo cuya hipotenusa es la flecha, así que $|v|^2 = x^2 + y^2$. Las fórmulas con ángulo salen de la trigonometría en ese mismo triángulo: $cos θ = v_x/|v|$ y $sen θ = v_y/|v|$, despejando $v_x = |v| cos θ$ y $v_y = |v| sen θ$. La suma componente a componente equivale a poner una flecha a continuación de la otra.",
    board: [
      { expr: "|v| = 10, θ = 30°", note: "datos: módulo y ángulo con el eje $x$" },
      { expr: "v_x = 10·cos 30°", note: "coseno: cateto adyacente al ángulo" },
      { expr: "v_x ≈ 10·0,866 ≈ 8,66" },
      { expr: "v_y = 10·sen 30° = 10·0,5 = 5", note: "seno: cateto opuesto" },
      { expr: "v ≈ (8,66; 5)", note: "control: $√(8,66^2 + 5^2) ≈ 10$ ✓" },
    ],
  },
};

export const productoEscalarLesson: Lesson = {
  id: "l-producto-escalar",
  title: "Producto escalar",
  subtitle: "Multiplicar vectores y obtener un número",
  subjectId: "algebra-a",
  topicIds: ["t-producto-escalar"],
  estimatedMinutes: 10,
  prerequisites: ["t-vectores"],
  cards: [
    intro("Producto escalar", "Cómo se calcula el producto escalar en ℝ² y ℝ³ y qué dice sobre el ángulo entre dos vectores.", "Es uno de los primeros temas de Álgebra A: sirve para calcular ángulos, detectar perpendicularidad y, en Física, para calcular el trabajo de una fuerza."),
    explain(
      "La cuenta",
      "Para $u = (u_1, u_2)$ y $v = (v_1, v_2)$:\n\n$u · v = u_1 v_1 + u_2 v_2$\n\nEn $ℝ^3$ se agrega $+ u_3 v_3$. El resultado es un **número** (un escalar), no un vector.",
      { tag: "matematico" },
    ),
    example("Ejemplo resuelto", "Calculá $(2, −1, 3) · (4, 5, −2)$", ["$2·4 = 8$", "$(−1)·5 = −5$", "$3·(−2) = −6$", "$8 − 5 − 6 = −3$"], "−3"),
    explain(
      "Qué significa",
      "$u · v = |u|·|v|·cos(θ)$, donde $θ$ es el ángulo entre ellos. Entonces:\n\n• $u·v > 0$: ángulo agudo (apuntan «parecido»).\n• $u·v = 0$: **perpendiculares** (ortogonales).\n• $u·v < 0$: ángulo obtuso.",
      { tag: "intuitivo" },
    ),
    board(
      "Pizarra: el ángulo entre dos vectores",
      [
        row("u = (1, 1), v = (0, 2)"),
        row("u·v = 1·0 + 1·2 = 2", "producto escalar con componentes"),
        row("|u| = √2, |v| = 2", "módulos con Pitágoras"),
        row("cos θ = 2/(2√2)", "despejamos de $u·v = |u||v| cos θ$"),
        row("cos θ = 1/√2 ≈ 0,707"),
        row("θ = 45°", "el ángulo cuyo coseno es $0,707$"),
      ],
    ),
    quiz("Para pensar", {
      id: "q-ortogonal",
      subjectId: "algebra-a",
      topicId: "t-producto-escalar",
      prompt: "¿Son perpendiculares $u = (3, 2)$ y $v = (−2, 3)$?",
      options: ["Sí, porque u·v = 0", "No, porque u·v = 12", "No se puede saber sin dibujar"],
      answer: 0,
      explanation: "u·v = 3·(−2) + 2·3 = −6 + 6 = 0. Producto escalar cero ⇔ vectores perpendiculares.",
      hints: ["Calculá el producto escalar.", "3·(−2) + 2·3.", "¿Qué significa que dé 0?"],
      errors: { 1: ["vectores", "Multiplicaste cruzado. Es x con x e y con y: 3·(−2) + 2·3 = 0."] },
    }, true),
    practice("Tu turno", "producto-escalar", 2, 3),
    practice("Tu turno", "producto-escalar", 4, 9),
    summary(["u·v = u₁v₁ + u₂v₂ (+ u₃v₃).", "El resultado es un número.", "u·v = 0 ⇔ perpendiculares.", "u·v = |u||v|cos θ."]),
  ],
  tutor: {
    normal: "El producto escalar (o interno) de dos vectores es la suma de los productos de sus componentes. Equivale a |u||v|cos θ, por lo que indica el ángulo entre ellos.",
    simple: "Multiplicá x con x, y con y, y sumá. Si da cero, los vectores forman un ángulo recto.",
    nino: "Pensá en remolcar un auto con una soga. Si tirás en la misma dirección en que se mueve, todo tu esfuerzo sirve; si tirás inclinado, solo sirve una parte; si tirás perpendicular (de costado), no lo hacés avanzar nada. El producto escalar mide exactamente esa «parte útil»: es máximo alineado y cero en ángulo recto.",
    ejemplo: "(1, 2)·(3, 4) = 3 + 8 = 11 (agudo). (2, 1)·(−1, −3) = −2 − 3 = −5 (obtuso). (4, −2)·(1, 2) = 4 − 4 = 0 (perpendiculares).",
    visual: { type: "vector", x: 3, y: 2, showSum: true },
    visualText: "Mové los vectores: cuando forman ángulo recto, el producto escalar vale 0.",
    fromZero: "Un vector en el plano se escribe con dos números, por ejemplo $u = (3, 2)$. El **producto escalar** es una forma de combinar dos vectores para obtener **un número**: multiplicás las primeras componentes entre sí, las segundas entre sí, y sumás. Con $u = (3, 2)$ y $v = (1, 4)$: $3·1 + 2·4 = 11$. Ese número mide qué tan «alineados» están: si apuntan parecido da positivo; si forman ángulo recto da cero; si apuntan a lados opuestos da negativo. En tres dimensiones es igual, con una tercera componente.",
    why: "Porque es la herramienta más directa para medir ángulos y detectar perpendicularidad sin dibujar, algo que en Álgebra se usa para rectas, planos y proyecciones. En Física, el trabajo de una fuerza es un producto escalar: solo cuenta la parte de la fuerza que va en la dirección del movimiento.",
    origin: "La conexión con el ángulo sale del teorema del coseno aplicado al triángulo formado por $u$, $v$ y $u − v$: $|u − v|^2 = |u|^2 + |v|^2 − 2|u||v| cos θ$. Si desarrollás $|u − v|^2$ con componentes, aparece $|u|^2 + |v|^2 − 2(u_1v_1 + u_2v_2)$. Comparando, $u_1v_1 + u_2v_2 = |u||v| cos θ$.",
    board: [
      { expr: "(2, −1, 3)·(1, 5, 1)" },
      { expr: "2·1 + (−1)·5 + 3·1", note: "componente con componente" },
      { expr: "2 − 5 + 3" },
      { expr: "0", note: "producto cero: los vectores son perpendiculares" },
    ],
  },
};

export const mruLesson: Lesson = {
  id: "l-mru",
  title: "Movimiento rectilíneo uniforme",
  subtitle: "Velocidad constante",
  subjectId: "fisica",
  topicIds: ["t-mru"],
  estimatedMinutes: 12,
  prerequisites: ["t-despeje", "t-unidades"],
  cards: [
    intro("MRU", "Describir un movimiento en línea recta a velocidad constante con una ecuación y un gráfico.", "Es el primer modelo de la Cinemática (Unidad 2 de Física). Todo lo que viene después (MRUV, tiro vertical) se construye sobre esta idea."),
    explain(
      "Posición, tiempo y velocidad",
      "Elegimos un eje (una recta con un 0 y un sentido positivo). La **posición** $x$ dice dónde está el móvil. La **velocidad** $v$ dice cuántos metros cambia la posición por segundo.\n\nSi $v$ es negativa, el móvil va en el sentido negativo del eje.\n\nDale play: con velocidad constante, las marcas de cada segundo quedan a la misma distancia.",
      { tag: "intuitivo", widget: { type: "motion", v0: 5, a: 0 } },
    ),
    quiz("Pregunta rápida", {
      id: "q3-mru-v",
      subjectId: "fisica",
      topicId: "t-mru",
      prompt: "Un móvil va a $v = 3$ m/s constante. ¿Cuánto cambia su posición en 4 s?",
      options: ["12 m", "7 m", "0,75 m"],
      answer: 0,
      explanation: "Cada segundo avanza 3 m; en 4 s, 3 · 4 = 12 m.",
      hints: ["v dice cuántos metros por segundo.", "Son 4 segundos.", "3 · 4."],
      errors: { 1: ["calculo", "Sumaste 3 + 4. Hay que multiplicar velocidad por tiempo."], 2: ["despeje", "Dividiste 3 ÷ 4. El desplazamiento es v · t."] },
    }),
    explain(
      "La ecuación",
      "Si la velocidad no cambia:\n\n$x(t) = x_0 + v·t$\n\n$x_0$: posición inicial (en $t = 0$). $v·t$: cuánto se desplazó. Es una **función lineal** del tiempo: la pendiente es la velocidad.",
      { tag: "matematico" },
    ),
    board(
      "Pizarra: ¿cuándo llega?",
      [
        row("x(t) = −40 + 8t", "parte de $x_0 = −40$ m a $8$ m/s"),
        row("80 = −40 + 8t", "queremos saber cuándo está en $x = 80$ m"),
        row("120 = 8t", "sumamos 40 en ambos lados"),
        row("t = 15", "dividimos por 8: a los 15 s"),
      ],
      "Un ciclista arranca 40 m antes del origen. ¿Cuándo pasa por $x = 80$ m?",
      "Control: $−40 + 8·15 = −40 + 120 = 80$ ✓.",
    ),
    explain(
      "Simulación",
      "Ajustá la posición inicial y la velocidad (dejá la aceleración en 0) y mirá el movimiento y su gráfico $x(t)$:",
      { widget: { type: "kinematics", x0: 0, v0: 5, a: 0 } },
    ),
    example("Ejemplo resuelto", "Un auto está en $x_0 = 20$ m y se mueve a $v = 15$ m/s. ¿Dónde está a los 4 s?", ["$x(4) = 20 + 15·4$", "$= 20 + 60$", "$= 80$ m"], "80 m"),
    practice("Ejercicio guiado", "mru", 2, 6, true),
    practice("Tu turno", "mru", 3, 14),
    quiz("Para pensar", {
      id: "q-mru-signo",
      subjectId: "fisica",
      topicId: "t-mru",
      prompt: "Un móvil tiene $x(t) = 50 − 10t$ (en m y s). ¿Qué está pasando?",
      options: ["Arranca en 50 m y se mueve hacia el sentido negativo a 10 m/s", "Arranca en 10 m y avanza a 50 m/s", "Está frenando"],
      answer: 0,
      explanation: "Comparando con x = x₀ + v·t: x₀ = 50 m y v = −10 m/s. Velocidad negativa = se mueve hacia el sentido negativo del eje, a velocidad constante (no frena).",
      hints: ["Compará con x(t) = x₀ + v·t.", "¿Qué número está solo y cuál multiplica a t?", "v = −10: ¿qué indica el signo?"],
      errors: { 2: ["velocidad-aceleracion", "Una velocidad negativa NO significa frenar: significa ir hacia el sentido negativo. Frenar sería que la velocidad cambie, y en el MRU no cambia."] },
    }),
    practice("Mini desafío", "mru", 5, 27),
    summary(["MRU: la velocidad es constante.", "x(t) = x₀ + v·t.", "En el gráfico x(t), la pendiente es la velocidad.", "v negativa = sentido negativo, no «frenar»."]),
  ],
  tutor: {
    normal: "En el MRU la velocidad es constante, por lo que la posición es una función lineal del tiempo: x(t) = x₀ + v·t. El desplazamiento en un intervalo es v·Δt.",
    simple: "Si vas siempre a la misma velocidad, cada segundo avanzás lo mismo. Posición = dónde empezaste + lo que avanzaste.",
    nino: "Una cinta transportadora: cada segundo mueve tu valija 2 metros. Si la valija empezó en el metro 3, a los 5 segundos está en 3 + 2·5 = 13.",
    ejemplo: "x₀ = 100 m, v = −5 m/s (va hacia el origen). A los 4 s: x = 100 − 20 = 80 m. Llega al origen cuando 100 − 5t = 0, o sea a los 20 s.",
    visual: { type: "motion", v0: 4, a: 0 },
    visualText: "Dale play: con velocidad constante, en cada segundo el móvil recorre la misma distancia.",
    fromZero: "Para describir un movimiento en línea recta, primero se elige una referencia: una recta con un punto 0 y un sentido positivo, como una regla apoyada en la ruta. La **posición** $x$ dice en qué marca de la regla está el móvil. El **tiempo** $t$ se cuenta desde que empezamos a mirar. La **velocidad** dice cuántos metros cambia la posición en cada segundo. Si esa velocidad no cambia, cada segundo el móvil avanza lo mismo: después de $t$ segundos avanzó $v·t$. Su posición es donde empezó más lo que avanzó: $x = x_0 + v·t$.",
    why: "Porque es el modelo de movimiento más simple y el punto de partida de toda la cinemática. Sirve para planificar tiempos de viaje, encuentros entre dos móviles y, sobre todo, para entender la idea de que la velocidad es la pendiente del gráfico posición-tiempo, que después se generaliza en la derivada.",
    origin: "Sale de la definición de velocidad media: $v = Δx/Δt$. Si la velocidad es constante, ese cociente vale lo mismo en cualquier intervalo. Tomando desde $t = 0$ (posición $x_0$) hasta un instante $t$ (posición $x$): $v = (x − x_0)/(t − 0)$. Despejando: $x = x_0 + v·t$.",
    board: [
      { expr: "Δx = v·t", note: "un móvil a 25 m/s tiene que recorrer 300 m" },
      { expr: "300 = 25·t", note: "reemplazamos los datos" },
      { expr: "t = 300/25", note: "dividimos ambos lados por 25" },
      { expr: "t = 12", note: "tarda 12 s" },
    ],
  },
};

export const mruvLesson: Lesson = {
  id: "l-mruv",
  title: "Movimiento uniformemente variado",
  subtitle: "Cuando la velocidad cambia",
  subjectId: "fisica",
  topicIds: ["t-mruv"],
  estimatedMinutes: 12,
  prerequisites: ["t-mru"],
  cards: [
    intro("MRUV", "Qué es la aceleración y las dos ecuaciones del movimiento con aceleración constante.", "El MRUV es el corazón de la Cinemática del CBC: caída libre, tiro vertical, frenadas y arranques se resuelven con estas ecuaciones."),
    explain(
      "Aceleración",
      "La **aceleración** dice cuánto cambia la **velocidad** por segundo. $a = 2$ m/s² significa: cada segundo, la velocidad aumenta 2 m/s.\n\n¡No confundas! La velocidad cambia la **posición**; la aceleración cambia la **velocidad**.\n\nDale play: ahora las marcas de cada segundo se van separando.",
      { tag: "intuitivo", widget: { type: "motion", v0: 2, a: 2 } },
    ),
    quiz("Pregunta rápida", {
      id: "q3-mruv-a",
      subjectId: "fisica",
      topicId: "t-mruv",
      prompt: "Un móvil va a $2$ m/s y acelera a $3$ m/s². ¿Qué velocidad tiene 1 s después?",
      options: ["5 m/s", "3 m/s", "6 m/s"],
      answer: 0,
      explanation: "La aceleración suma 3 m/s de velocidad por cada segundo: 2 + 3 = 5 m/s.",
      hints: ["a dice cuánto cambia la velocidad por segundo.", "Pasó 1 segundo.", "2 + 3·1."],
      errors: { 1: ["velocidad-aceleracion", "La aceleración no es la velocidad: es cuánto se le SUMA a la velocidad cada segundo."], 2: ["calculo", "Multiplicaste 2 · 3. La velocidad nueva es la vieja más a·t."] },
    }),
    explain(
      "Las dos ecuaciones",
      "Con aceleración constante:\n\n$v(t) = v_0 + a·t$\n$x(t) = x_0 + v_0·t + ½·a·t^2$\n\nLa posición tiene $t^2$ porque la velocidad va creciendo: cada segundo se avanza un poco más que el anterior. El gráfico $x(t)$ es una **parábola**.",
      { tag: "matematico" },
    ),
    board(
      "Pizarra: usar las dos ecuaciones",
      [
        row("v = 4 + 2·5", "$v_0 = 4$ m/s, $a = 2$ m/s², $t = 5$ s"),
        row("v = 14", "m/s"),
        row("x = 0 + 4·5 + ½·2·5^2", "posición, con $x_0 = 0$"),
        row("x = 20 + ½·2·25", "primero la potencia: $5^2 = 25$"),
        row("x = 20 + 25"),
        row("x = 45", "metros"),
      ],
    ),
    explain(
      "Simulación",
      "Ahora poné una aceleración distinta de cero. Probá: velocidad inicial positiva y aceleración negativa. ¿Qué pasa?",
      { widget: { type: "kinematics", x0: 0, v0: 10, a: -2 } },
    ),
    example("Ejemplo resuelto", "Un auto parte del reposo ($v_0 = 0$) con $a = 3$ m/s². ¿Velocidad y posición a los 4 s?", ["$v(4) = 0 + 3·4 = 12$ m/s", "$x(4) = 0 + 0·4 + ½·3·4^2$", "$= ½·3·16 = 24$ m"], "12 m/s y 24 m"),
    practice("Ejercicio guiado", "mruv", 1, 3, true),
    practice("Tu turno", "mruv", 3, 7),
    explain(
      "Frenar o acelerar",
      "Si $v$ y $a$ tienen el **mismo signo**, el móvil va cada vez más rápido. Si tienen **signos opuestos**, frena.\n\nUn auto que va a 20 m/s y frena con $a = −4$ m/s² se detiene cuando $v = 0$: $0 = 20 − 4t$ → $t = 5$ s.",
    ),
    practice("Tu turno", "cinematica-conceptos", 3, 1),
    practice("Tu turno", "mruv", 4, 15),
    practice("Mini desafío", "mruv", 5, 20),
    summary(["La aceleración cambia la velocidad; la velocidad cambia la posición.", "v = v₀ + a·t.", "x = x₀ + v₀·t + ½·a·t².", "Mismo signo v y a: acelera. Signos opuestos: frena."]),
  ],
  tutor: {
    normal: "En el MRUV la aceleración es constante: la velocidad varía linealmente (v = v₀ + at) y la posición cuadráticamente (x = x₀ + v₀t + ½at²).",
    simple: "La aceleración es «cuánto sube la velocidad por segundo». Si a = 2, la velocidad va 0, 2, 4, 6... y la distancia recorrida crece cada vez más rápido.",
    nino: "Cuando un colectivo arranca desde la parada, en el primer segundo apenas se mueve, en el siguiente avanza un poco más y así: cada segundo recorre más que el anterior porque va cada vez más rápido. Cuando llega a la otra parada y frena, pasa lo contrario. Esa variación de la velocidad es la aceleración.",
    ejemplo: "v₀ = 5 m/s, a = 2 m/s². A los 3 s: v = 5 + 2·3 = 11 m/s; x = 5·3 + ½·2·9 = 15 + 9 = 24 m.",
    visual: { type: "motion", v0: 0, a: 2 },
    visualText: "Parte del reposo con a = 2 m/s²: mirá cómo cada segundo recorre más que el anterior.",
    fromZero: "Cuando un auto arranca, su velocidad no es fija: crece. La **aceleración** mide cuánto cambia la velocidad en cada segundo. Si $a = 2$ m/s², cada segundo la velocidad aumenta 2 m/s: 0, 2, 4, 6… Por eso la velocidad después de $t$ segundos es la inicial más lo que ganó: $v = v_0 + a·t$. La posición es más sutil: como cada segundo va más rápido que el anterior, cada segundo recorre más metros. Por eso la fórmula de la posición tiene un $t^2$: $x = x_0 + v_0·t + ½·a·t^2$. Si la aceleración es negativa y la velocidad positiva, el móvil frena.",
    why: "Porque la mayoría de los movimientos reales cambian de velocidad: arranques, frenadas, caídas. El MRUV es el modelo que permite calcular distancias de frenado, tiempos de llegada y, con $a = −9,8$ m/s², todo el tiro vertical. Es el núcleo de la primera parte de Física del CBC.",
    origin: "$v = v_0 + a·t$ sale de la definición de aceleración constante: $a = (v − v_0)/t$. Para la posición, en el gráfico velocidad-tiempo el desplazamiento es el área bajo la recta: un trapecio con lados $v_0$ y $v$ y base $t$. Su área es $(v_0 + v)/2 · t = (v_0 + v_0 + a·t)/2 · t = v_0·t + ½·a·t^2$.",
    board: [
      { expr: "0 = 20 − 4t", note: "auto a 20 m/s que frena con $a = −4$ m/s²: se detiene cuando $v = 0$" },
      { expr: "t = 5", note: "sumamos $4t$ y dividimos por 4: frena en 5 s" },
      { expr: "x = 20·5 + ½·(−4)·5^2", note: "distancia de frenado" },
      { expr: "x = 100 − 50" },
      { expr: "x = 50", note: "recorre 50 m hasta detenerse" },
    ],
  },
};

export const caidaLibreLesson: Lesson = {
  id: "l-caida-libre",
  title: "Caída libre y tiro vertical",
  subtitle: "MRUV con g = 9,8 m/s²",
  subjectId: "fisica",
  topicIds: ["t-caida-libre"],
  estimatedMinutes: 12,
  prerequisites: ["t-mruv"],
  cards: [
    intro("Caída libre", "Aplicar el MRUV a objetos que caen o se lanzan verticalmente.", "Es un clásico de los parciales de Física: altura máxima, tiempo de vuelo, velocidad al tocar el suelo."),
    explain(
      "Es un MRUV",
      "Sin rozamiento del aire, todo objeto cerca de la superficie terrestre tiene la misma aceleración: $g ≈ 9,8$ m/s², hacia abajo.\n\nSi tomamos el eje $y$ hacia arriba: $a = −9,8$ m/s². Las ecuaciones son las del MRUV:\n\n$v(t) = v_0 − 9,8·t$\n$y(t) = y_0 + v_0·t − 4,9·t^2$",
      { tag: "matematico" },
    ),
    quiz("Pregunta rápida", {
      id: "q3-cl-signo",
      subjectId: "fisica",
      topicId: "t-caida-libre",
      prompt: "Con el eje $y$ hacia arriba, ¿cuánto vale la aceleración de una pelota **mientras sube**?",
      options: ["$−9,8$ m/s²", "$+9,8$ m/s²", "$0$"],
      answer: 0,
      explanation: "La gravedad apunta siempre hacia abajo, suba o baje la pelota. Con el eje hacia arriba, a = −9,8 m/s² durante todo el vuelo.",
      hints: ["¿Hacia dónde tira la gravedad?", "Siempre hacia abajo.", "El eje apunta hacia arriba: el signo es negativo."],
      errors: { 1: ["velocidad-aceleracion", "Que la pelota suba indica el signo de la VELOCIDAD, no de la aceleración. La gravedad tira hacia abajo."], 2: ["velocidad-aceleracion", "La gravedad nunca se apaga: la aceleración es −9,8 m/s² todo el tiempo."] },
    }),
    explain(
      "Simulación: tiro vertical",
      "Interpretá el eje como vertical: lanzá hacia arriba con $v_0 = 19,6$ m/s y $a = −9,8$ m/s². ¿Cuándo llega arriba? ¿Cuándo vuelve al punto de partida?",
      { widget: { type: "kinematics", x0: 0, v0: 19.6, a: -9.8 } },
    ),
    quiz("Pregunta rápida", {
      id: "q3-cl-subida",
      subjectId: "fisica",
      topicId: "t-caida-libre",
      prompt: "Lanzada hacia arriba a $19,6$ m/s, ¿cuánto tarda en llegar al punto más alto?",
      options: ["2 s", "1 s", "4 s"],
      answer: 0,
      explanation: "Pierde 9,8 m/s por segundo: 19,6 ÷ 9,8 = 2 s hasta que la velocidad llega a 0.",
      hints: ["Arriba, la velocidad es 0.", "Cada segundo pierde 9,8 m/s.", "19,6 ÷ 9,8."],
      errors: { 2: ["conceptual", "4 s es el vuelo completo (subir y volver a bajar). La subida es la mitad."] },
    }),
    explain(
      "La altura máxima",
      "Arriba de todo, la pelota deja de subir: su **velocidad es 0**. Pero la gravedad sigue actuando: su **aceleración sigue siendo −9,8 m/s²**.\n\nTiempo de subida: $0 = v_0 − 9,8t$ → $t = v_0/9,8$. Reemplazando en $y(t)$: $h_{máx} = v_0^2/(2·9,8)$.",
      { tag: "intuitivo" },
    ),
    board(
      "Pizarra: altura máxima",
      [
        row("0 = 24,5 − 9,8·t", "lanzada a 24,5 m/s; en la altura máxima $v = 0$"),
        row("t = 24,5/9,8 = 2,5", "tiempo de subida: 2,5 s"),
        row("y = 24,5·2,5 − 4,9·2,5^2", "reemplazamos ese tiempo en $y(t)$"),
        row("y = 61,25 − 30,625", "$2,5^2 = 6,25$ y $4,9·6,25 = 30,625$"),
        row("y = 30,625", "unos 30,6 m"),
      ],
      undefined,
      "Control con la fórmula directa: $24,5^2/(2·9,8) = 600,25/19,6 = 30,625$ ✓.",
    ),
    example("Ejemplo resuelto", "Se lanza hacia arriba a 29,4 m/s. ¿Tiempo de subida y altura máxima?", ["$0 = 29,4 − 9,8·t$ → $t = 3$ s", "$y(3) = 29,4·3 − 4,9·3^2$", "$= 88,2 − 44,1 = 44,1$ m"], "3 s y 44,1 m"),
    explain(
      "¿Y si se lanza en diagonal?",
      "Un tiro oblicuo son dos movimientos a la vez: en vertical, exactamente el tiro vertical que acabás de ver ($a = −9,8$ m/s²); en horizontal, un MRU (nada acelera hacia los costados).\n\nDale play y cambiá el ángulo: la altura máxima depende solo de la parte vertical de la velocidad.",
      { tag: "intuitivo", widget: { type: "projectile", v0: 20, angle: 60, h0: 0 } },
    ),
    practice("Ejercicio guiado", "caida-libre", 2, 2, true),
    practice("Tu turno", "caida-libre", 3, 9),
    practice("Tu turno", "cinematica-conceptos", 3, 5),
    practice("Mini desafío", "caida-libre", 5, 12),
    summary(["Caída libre = MRUV con a = −9,8 m/s² (eje hacia arriba).", "En la altura máxima v = 0, pero a = −9,8 m/s².", "t_subida = v₀/g; h_máx = v₀²/(2g).", "Sin aire, todos los cuerpos caen igual."]),
  ],
  tutor: {
    normal: "La caída libre es un MRUV con aceleración g ≈ 9,8 m/s² dirigida hacia abajo, independiente de la masa. El tiro vertical es el mismo movimiento con velocidad inicial vertical.",
    simple: "Cuando tirás algo para arriba, cada segundo pierde 9,8 m/s de velocidad. Cuando la velocidad llega a 0, está arriba de todo, y empieza a caer.",
    nino: "Es como tirar las llaves hacia arriba para que te las agarren desde un balcón: salen rápido, van perdiendo velocidad, en el punto más alto quedan un instante «quietas» y, si nadie las agarra, vuelven a bajar ganando velocidad al mismo ritmo con que la perdieron. Con 20 m/s: al segundo van a 10,2 m/s y a los 2 s a 0,4 m/s.",
    ejemplo: "v₀ = 14,7 m/s: sube 14,7 ÷ 9,8 = 1,5 s y llega a 14,7² ÷ 19,6 ≈ 11,0 m. Vuelve a la mano a los 3 s, otra vez a 14,7 m/s pero hacia abajo.",
    visual: { type: "projectile", v0: 15, angle: 80, h0: 0 },
    visualText: "Casi vertical: la pelota sube frenando, se detiene un instante arriba y vuelve a bajar acelerando. Probá otros ángulos.",
    fromZero: "Si soltás una llave, cae; si la tirás hacia arriba, sube cada vez más lento, se detiene un instante y vuelve. Lo que la frena al subir y la acelera al bajar es la gravedad, que le cambia la velocidad en $9,8$ m/s cada segundo, siempre hacia abajo. O sea: es un movimiento con aceleración constante, el MRUV que ya viste, con $a = −9,8$ m/s² si el eje apunta hacia arriba. Con eso, las preguntas típicas se responden con dos ideas: en el punto más alto la velocidad es cero, y cuando vuelve al suelo la posición es cero.",
    why: "Porque es el primer caso real donde aplicás el MRUV completo, con signos, y es un clásico de los parciales: altura máxima, tiempo de vuelo, velocidad al tocar el suelo. Además es la parte vertical de cualquier tiro oblicuo, así que lo vas a reutilizar enseguida.",
    origin: "Las ecuaciones son las del MRUV con $a = −g$: $v = v_0 − g·t$ y $y = y_0 + v_0·t − ½·g·t^2$. La altura máxima sale de pedir $v = 0$: $t = v_0/g$; reemplazando, $h = v_0·(v_0/g) − ½·g·(v_0/g)^2 = v_0^2/g − v_0^2/(2g) = v_0^2/(2g)$. Que $g$ no dependa de la masa es un resultado experimental: sin aire, una pluma y un martillo caen juntos.",
    board: [
      { expr: "y = 20 − 4,9·t^2", note: "se suelta desde 20 m de altura ($v_0 = 0$)" },
      { expr: "0 = 20 − 4,9·t^2", note: "llega al suelo cuando $y = 0$" },
      { expr: "t^2 = 20/4,9 ≈ 4,08" },
      { expr: "t ≈ 2,02", note: "tarda unos 2,02 s" },
      { expr: "v = −9,8·2,02 ≈ −19,8", note: "llega a unos 19,8 m/s, hacia abajo" },
    ],
  },
};

export const fisicaLessons = [unidades, vectores, productoEscalarLesson, mruLesson, mruvLesson, caidaLibreLesson];
