/**
 * Lecciones de Introducción al Pensamiento Científico (IPC 040, UBA XXI,
 * programa 2026, Cátedra A). Unidades: ipc-u1 (La argumentación), ipc-u2 (La
 * revolución darwiniana), ipc-u3 (El cambio científico), ipc-u4 (La dimensión
 * ético-política de la ciencia).
 *
 * Todos los ejemplos son propios, escritos "en el estilo" de la cátedra.
 */
import type { BoardStep, LessonCard, Lesson } from "@/engine/types";
import { example, explain, intro, practice, quiz, summary } from "./helpers";

const S = "ipc";

const board = (title: string, steps: BoardStep[], introText?: string, outro?: string): LessonCard => ({ kind: "board", title, intro: introText, steps, outro });

// ═══════════════════════ Unidad 1 · La argumentación ═══════════════════════

export const ipcArgumentos: Lesson = {
  id: "l-ipc-argumentos",
  title: "¿Qué es un argumento?",
  subtitle: "Premisas, conclusión e indicadores",
  subjectId: S,
  topicIds: ["t-ipc-argumentos"],
  estimatedMinutes: 10,
  prerequisites: [],
  cards: [
    intro(
      "Argumentar no es solo afirmar",
      "Vas a distinguir el discurso argumentativo del informativo, reconocer premisas y conclusión, y usar los indicadores sin depender de ellos.",
      "Reconocer argumentos es la base de toda la Unidad 1 y aparece en los primeros ítems del parcial. Además, la ciencia misma avanza dando razones: sin argumentos no hay justificación.",
    ),
    explain(
      "Informar o argumentar",
      "Una receta da instrucciones. Una crónica cuenta lo que pasó. Una ficha describe un objeto. En ninguno de esos textos una afirmación se **apoya** en otra: es **discurso informativo**.\n\nHay **discurso argumentativo** cuando alguien ofrece razones para que aceptemos algo: «No salgas sin paraguas, **porque** el pronóstico anuncia tormenta».",
      { tag: "cotidiano" },
    ),
    quiz("Chequeo rápido", {
      id: "q-ipc-arg-1",
      subjectId: S,
      topicId: "t-ipc-argumentos",
      prompt: "¿Cuál de estos fragmentos es un **argumento**?",
      options: [
        "Si el tren se atrasa, llego tarde a la clase.",
        "El laboratorio queda en el segundo piso. Tiene doce mesadas y dos microscopios electrónicos.",
        "El tren se atrasó, así que voy a llegar tarde a la clase.",
        "Encendé la computadora, abrí el campus y descargá la guía.",
      ],
      answer: 2,
      explanation: "En la tercera opción «voy a llegar tarde» se apoya en «el tren se atrasó» («así que» indica la conclusión). El condicional solo relaciona dos enunciados sin afirmar ninguno; las otras dos son descripción e instrucciones.",
      hints: ["Buscá una afirmación que se apoye en otra.", "«Así que» es un indicador de conclusión.", "Un «si…, …» suelto no afirma ni concluye nada."],
      errors: {
        0: ["logica", "Un condicional solo no es un argumento: dice qué pasaría SI el tren se atrasa, pero no afirma que se atrase ni concluye nada."],
        1: ["interpretacion", "Es una descripción: discurso informativo."],
        3: ["interpretacion", "Son instrucciones: no se ofrecen razones para ninguna afirmación."],
      },
    }),
    explain(
      "Premisas, conclusión, indicadores",
      "Un **argumento** tiene **una** conclusión y **una o más** premisas.\n\n• Indicadores de **premisa**: porque, pues, ya que, puesto que, dado que.\n• Indicadores de **conclusión**: por lo tanto, luego, en consecuencia, por consiguiente, se sigue que.\n\nLos indicadores **ayudan pero no son necesarios**, y **no forman parte** ni de las premisas ni de la conclusión. La conclusión puede ir al principio, en el medio o al final.",
      { tag: "matematico" },
    ),
    board(
      "Desarmar un argumento",
      [
        { expr: "«Ana va a promocionar, ya que estudia todos los días y quien estudia todos los días promociona.»" },
        { expr: "Indicador: «ya que»", note: "introduce premisas: lo que está ANTES es la conclusión" },
        { expr: "P1: Ana estudia todos los días.", note: "primera razón" },
        { expr: "P2: Quien estudia todos los días promociona.", note: "segunda razón (la «y» separa dos premisas)" },
        { expr: "C: Ana va a promocionar.", note: "completa, con sujeto explícito y sin el indicador" },
      ],
      "Vamos a separar premisas y conclusión renglón por renglón.",
      "Siempre escribí la conclusión como una oración completa que se entienda sola.",
    ),
    example(
      "Conclusión en el medio",
      "«Los murciélagos tienen pelo; por lo tanto, son mamíferos, pues todo animal con pelo es un mamífero.» ¿Cuál es la conclusión?",
      ["«Por lo tanto» marca lo que sigue como conclusión: «son mamíferos».", "«Pues» introduce una premisa: «todo animal con pelo es un mamífero».", "La otra premisa es «Los murciélagos tienen pelo».", "La escribimos completa: «Los murciélagos son mamíferos»."],
      "Conclusión: «Los murciélagos son mamíferos».",
    ),
    practice("Ejercicio guiado", "ipc-es-argumento", 1, 5, true),
    explain(
      "Dos trampas clásicas",
      "**1. El condicional suelto.** «Si llueve, se suspende el partido» no es un argumento: no afirma que llueva ni concluye que se suspenda.\n\n**2. La conclusión incompleta.** Si el texto dice «…se sigue que es pura y bella», la conclusión no es «Es pura y bella» sino «La piedra es pura y bella». Y nunca incluyas el indicador: «Por lo tanto, …» no es la conclusión.",
      { tag: "intuitivo" },
    ),
    practice("Tu turno", "ipc-conclusion", 2, 7),
    practice("Un poco más difícil", "ipc-conclusion", 4, 12),
    practice("Desafío", "ipc-es-argumento", 5, 19),
    summary([
      "Argumento: una conclusión que se pretende apoyar en una o más premisas.",
      "Discurso informativo (describir, narrar, instruir) ≠ discurso argumentativo (dar razones).",
      "Indicadores de premisa: porque, ya que, pues. De conclusión: por lo tanto, luego, en consecuencia.",
      "Los indicadores ayudan, no son obligatorios y no forman parte de los enunciados.",
      "Un condicional solo no es un argumento. La conclusión se escribe completa.",
    ]),
  ],
  tutor: {
    normal: "Un argumento es un conjunto de enunciados en el que uno, la conclusión, se pretende establecer a partir de otros, las premisas, que se ofrecen como razones. El discurso es argumentativo cuando existe esa pretensión de apoyo; si solo describe, narra o instruye, es informativo.",
    simple: "Argumentar es dar razones. La conclusión es lo que querés que el otro acepte; las premisas son tus razones. Si nadie está dando razones para nada, no hay argumento.",
    nino: "Es como cuando le pedís a tus viejos salir el sábado: «Déjenme ir, porque ya terminé la tarea y vuelvo temprano». «Déjenme ir» es la conclusión; «terminé la tarea» y «vuelvo temprano» son las premisas.",
    ejemplo: "«Hoy hay paro de colectivos; por lo tanto, la clase será virtual.» Premisa: hoy hay paro de colectivos. Conclusión: la clase será virtual.",
    fromZero: "Un enunciado es una oración que afirma algo que puede ser verdadero o falso. A veces juntamos varios enunciados y usamos algunos para sostener otro: eso es un argumento. El enunciado sostenido es la conclusión; los que sostienen, las premisas. Para encontrarlos, preguntate: ¿qué se quiere probar acá? y ¿qué se da como razón?",
    why: "Distinguir argumentos de otros textos es el primer paso para evaluarlos. No podés decidir si un razonamiento es bueno si antes no sabés qué se pretende probar y con qué razones.",
    origin: "La idea viene de la lógica clásica: se analiza el lenguaje por la función que cumple cada enunciado. Los indicadores son pistas que el propio idioma ofrece para marcar esa función, por eso se los usa como guía pero no como requisito.",
    board: [
      { expr: "Texto: «Hay paro de colectivos; por lo tanto, la clase será virtual.»" },
      { expr: "Indicador de conclusión: «por lo tanto»", note: "lo que sigue es la conclusión" },
      { expr: "P: Hay paro de colectivos.", note: "la razón ofrecida" },
      { expr: "C: La clase será virtual.", note: "sin el indicador, completa" },
    ],
  },
};

export const ipcEnunciados: Lesson = {
  id: "l-ipc-enunciados",
  title: "Oraciones, proposiciones y tipos de enunciados",
  subtitle: "Qué se afirma y de cuántos casos se habla",
  subjectId: S,
  topicIds: ["t-ipc-enunciados"],
  estimatedMinutes: 9,
  prerequisites: ["t-ipc-argumentos"],
  cards: [
    intro(
      "No todo lo que se dice se puede evaluar",
      "Vas a distinguir oración de proposición, reconocer qué oraciones pueden ser verdaderas o falsas y clasificar enunciados según su alcance.",
      "El alcance de un enunciado (singular, universal, existencial, estadístico) decide cómo se lo verifica o refuta. Esa idea vuelve con fuerza en la Unidad 3, cuando se contrastan hipótesis científicas.",
    ),
    explain(
      "Oración y proposición",
      "La **oración** es el soporte material: las palabras. La **proposición** es lo que la oración afirma.\n\n• «Darwin escribió *El origen de las especies*» y «*El origen de las especies* fue escrito por Darwin» son dos oraciones con **la misma** proposición.\n• «El señor alquila una casa» es ambigua: puede expresar **dos** proposiciones.\n\nSolo las oraciones **declarativas** expresan proposiciones evaluables como V o F. Preguntas, órdenes y deseos, no.",
      { tag: "cotidiano" },
    ),
    quiz("Chequeo rápido", {
      id: "q-ipc-enun-1",
      subjectId: S,
      topicId: "t-ipc-enunciados",
      prompt: "¿Cuál de estas oraciones **no** expresa una proposición?",
      options: ["El cobre conduce la electricidad.", "¿El cobre conduce la electricidad?", "Ningún metal es transparente.", "Algunos estudiantes rinden libre."],
      answer: 1,
      explanation: "Una pregunta no afirma nada, así que no puede ser verdadera ni falsa. Las otras tres son declarativas (aunque alguna sea falsa, ¡igual es una proposición!).",
      hints: ["¿Tiene sentido decir «eso es verdad» de cada una?", "Preguntas, órdenes y deseos no son V ni F.", "Ser falsa no impide ser proposición."],
      errors: { 2: ["conceptual", "Puede ser falsa, pero afirma algo: expresa una proposición."], 0: ["conceptual", "Es declarativa: afirma algo verdadero o falso."], 3: ["conceptual", "Es declarativa: afirma que hay al menos un caso."] },
    }),
    explain(
      "Tipos por alcance",
      "• **Singular**: habla de un individuo. «Plutón es un planeta enano.»\n• **Universal**: de todos los miembros de una clase. «Todos los metales se dilatan con el calor.»\n• **Existencial**: afirma que hay al menos uno. «Hay aves que no vuelan.»\n• **Estadístico**: una proporción. «El 80% de los fumadores tose.»\n\nOtra clasificación, independiente: **simple** (sin conectivas) o **complejo** (con «y», «o», «si…», «no»).",
      { tag: "matematico" },
    ),
    board(
      "Cómo se decide cada tipo",
      [
        { expr: "Singular → V si el individuo tiene la propiedad", note: "se mira ese caso" },
        { expr: "Universal → un contraejemplo lo vuelve F", note: "pero no se verifica revisando casos si la clase es infinita" },
        { expr: "Existencial → un caso lo vuelve V", note: "para que sea F hay que revisar TODO el conjunto" },
        { expr: "Estadístico → ni un caso a favor ni uno en contra lo deciden", note: "admite excepciones por definición" },
      ],
      "La asimetría entre universales y existenciales es clave:",
    ),
    example(
      "Refutar un existencial",
      "«Algunos cisnes son negros.» ¿Alcanza con encontrar un cisne blanco para refutarlo?",
      ["Es existencial: afirma que hay al menos un cisne negro.", "Un cisne blanco no contradice eso: puede haber otros negros.", "Para que sea falso, NINGÚN cisne debería ser negro: habría que revisarlos a todos."],
      "No alcanza: un existencial no se refuta con un caso en contra.",
    ),
    practice("Ejercicio guiado", "ipc-alcance-enunciado", 1, 3, true),
    explain(
      "Error típico: «todos» no siempre es universal abierto",
      "Un «todos» puede referirse a un conjunto **finito y accesible**: «Todos los perros que se vacunaron ayer en esta veterinaria ladraron». Ese enunciado se controla mirando los casos. En la Unidad 3 lo vas a llamar **muestral**.\n\nY otro clásico: para refutar «Algunos S son P» **no basta** un S que no sea P.",
      { tag: "intuitivo" },
    ),
    practice("Tu turno", "ipc-alcance-enunciado", 3, 8),
    practice("Desafío", "ipc-alcance-enunciado", 5, 14),
    summary([
      "Oración = las palabras; proposición = lo que se afirma. Dos oraciones pueden expresar la misma proposición.",
      "Solo las oraciones declarativas son verdaderas o falsas.",
      "Por alcance: singular, universal, existencial, estadístico.",
      "Universal: refutable con un contraejemplo. Existencial: verificable con un caso.",
      "Estadístico: ningún caso aislado lo decide.",
    ]),
  ],
  tutor: {
    normal: "La oración es una entidad lingüística; la proposición, su contenido, que es lo evaluable como verdadero o falso. Según su alcance, los enunciados son singulares, universales, existenciales o estadísticos, y cada tipo tiene condiciones distintas de verificación y refutación.",
    simple: "Una oración son las palabras; la proposición es lo que querés decir con ellas. Y según de cuántos casos hables (uno, todos, alguno, un porcentaje), cambia lo que hace falta para mostrar que es verdad o mentira.",
    nino: "Si decís «todos los alfajores de la caja son de chocolate», con encontrar uno de dulce de leche ya te equivocaste. Si decís «hay algún alfajor de chocolate», con encontrar uno ya tenés razón.",
    ejemplo: "«Todos los planetas del sistema solar giran alrededor del Sol» es universal; «Hay planetas con anillos», existencial; «El 30% de los estudiantes trabaja», estadístico.",
    fromZero: "Hablamos con oraciones. Algunas preguntan, otras ordenan y otras afirman. Solo las que afirman pueden ser verdaderas o falsas: lo que afirman se llama proposición. Después miramos de cuántas cosas habla la afirmación: de una sola, de todas, de alguna, o de una proporción.",
    why: "Saber el alcance te dice qué evidencia hace falta. Es la misma lógica con la que la ciencia pone a prueba sus hipótesis: una ley universal puede caer con un solo caso en contra.",
    origin: "La distinción proviene de la lógica de cuantificadores: «todos» (cuantificador universal) y «algún» (existencial). Un universal es falso si existe un contraejemplo; un existencial es verdadero si existe un caso: por eso se comportan de manera simétrica e inversa.",
    board: [
      { expr: "«Todos los S son P»", note: "universal" },
      { expr: "Un S que no es P → F", note: "basta un contraejemplo" },
      { expr: "«Algún S es P»", note: "existencial" },
      { expr: "Un S que es P → V", note: "basta un caso" },
    ],
  },
};

export const ipcConectivas: Lesson = {
  id: "l-ipc-conectivas",
  title: "Conectivas y tablas de verdad",
  subtitle: "Condiciones de verdad de los enunciados complejos",
  subjectId: S,
  topicIds: ["t-ipc-conectivas"],
  estimatedMinutes: 11,
  prerequisites: ["t-ipc-enunciados"],
  cards: [
    intro(
      "La verdad de lo complejo depende de sus partes",
      "Vas a calcular el valor de verdad de enunciados con «y», «o», «o bien… o bien», «si…, entonces» y «si y solo si», usando sus tablas.",
      "Es el ítem más mecánico del parcial: si sabés las tablas, es un punto seguro. Y las tablas son la herramienta para decidir validez y tautologías.",
    ),
    explain(
      "La promesa rota",
      "Te dicen: «Si aprobás el parcial, te invito a comer». ¿Cuándo **mintieron**?\n\nSolo si aprobaste y **no** te invitaron. Si no aprobaste, la promesa no se rompió, te inviten o no.\n\nAsí funciona el condicional: es **falso en un único caso**, antecedente verdadero y consecuente falso.",
      { tag: "cotidiano" },
    ),
    quiz("Chequeo rápido", {
      id: "q-ipc-con-1",
      subjectId: S,
      topicId: "t-ipc-conectivas",
      prompt: "A = «Llueve» es verdadera y B = «Hace frío» es falsa. ¿Qué valor tiene «Llueve, **pero** no hace frío»?",
      options: ["Verdadero", "Falso"],
      answer: 0,
      explanation: "Para la lógica, «pero» es una conjunción, igual que «y». «Llueve» es V y «no hace frío» es V (porque B es F): la conjunción de dos verdaderas es verdadera.",
      hints: ["¿Qué conectiva es «pero»?", "«Pero» = «y».", "Calculá primero «no hace frío»."],
      errors: { 1: ["logica", "«Pero» funciona como «y». Las dos partes son V («llueve» V; «no hace frío» V), así que la conjunción es V."] },
    }),
    explain(
      "Las tablas, en una pantalla",
      "• **No A**: invierte el valor.\n• **A y B**: V solo si ambas son V.\n• **A o B** (inclusiva): F solo si ambas son F.\n• **O bien A o bien B** (exclusiva): V si **exactamente una** es V.\n• **Si A, entonces B**: F solo si A es V y B es F.\n• **A si y solo si B**: V si **tienen el mismo valor** (también con ambas F).",
      { tag: "matematico" },
    ),
    board(
      "Evaluar paso a paso",
      [
        { expr: "A = V, B = V, C = F", note: "datos" },
        { expr: "¬B = F", note: "la negación invierte el valor de B" },
        { expr: "A ∧ ¬B = V ∧ F = F", note: "la conjunción necesita las dos verdaderas" },
        { expr: "(A ∧ ¬B) → C = F → F", note: "reemplazamos el antecedente ya calculado" },
        { expr: "F → F = V", note: "un condicional con antecedente falso es verdadero" },
      ],
      "Evaluamos «Si A y no B, entonces C» (en símbolos: (A ∧ ¬B) → C), de adentro hacia afuera:",
      "Resultado: el enunciado es verdadero.",
    ),
    example(
      "La exclusiva",
      "A y B son verdaderas. ¿Qué valor tienen «A o B» y «O bien A o bien B»?",
      ["«A o B» (inclusiva) solo es F si ambas son F: acá es V.", "«O bien A o bien B» (exclusiva) es V si exactamente una es V.", "Como son verdaderas las dos, la exclusiva es F."],
      "«A o B» = V; «O bien A o bien B» = F.",
    ),
    practice("Ejercicio guiado", "ipc-valor-verdad", 1, 4, true),
    explain(
      "Errores que más se repiten",
      "• Creer que un condicional con antecedente **falso** es falso: es **verdadero**.\n• Olvidar que el bicondicional con **F y F** es **V**: lo que importa es que coincidan.\n• Tratar «pero», «aunque» o «además» como algo distinto de «y».\n• Leer «o bien… o bien» como inclusiva.\n\n¿Cómo saber si una «o» sin marcas es exclusiva? Preguntate si la oración seguiría siendo verdadera con ambas partes verdaderas.",
      { tag: "intuitivo" },
    ),
    practice("Tu turno", "ipc-valor-verdad", 3, 9),
    practice("Desafío", "ipc-valor-verdad", 5, 13),
    summary([
      "La verdad de un enunciado complejo depende solo de la verdad de sus partes.",
      "Conjunción: V solo si ambas V. Disyunción inclusiva: F solo si ambas F. Exclusiva: V si exactamente una V.",
      "Condicional: F solo con antecedente V y consecuente F.",
      "Bicondicional: V cuando coinciden (V-V o F-F).",
      "Resolvé de adentro hacia afuera, reemplazando por V o F.",
    ]),
  ],
  tutor: {
    normal: "Las conectivas son veritativo-funcionales: el valor de verdad del enunciado complejo queda determinado por los valores de sus componentes según la tabla de cada conectiva. El condicional material es falso únicamente cuando el antecedente es verdadero y el consecuente falso; el bicondicional es verdadero cuando ambos lados coinciden.",
    simple: "Cada conectiva tiene una regla fija. «Y» pide que todo sea cierto. «O» se conforma con una. «Si…, entonces» solo falla cuando pasa lo primero y no pasa lo segundo.",
    nino: "Pensalo como una promesa: «Si ordenás tu pieza, vamos a la plaza». Solo es mentira si ordenaste y no fueron. Si no ordenaste, nadie mintió.",
    ejemplo: "A = V y B = F: «A y B» = F; «A o B» = V; «Si A, entonces B» = F; «Si B, entonces A» = V; «A si y solo si B» = F.",
    fromZero: "Un enunciado simple es V o F. Cuando los unimos con palabras como «y», «o», «si… entonces», armamos enunciados complejos. Para saber si el complejo es V o F no hace falta saber de qué habla: alcanza con saber el valor de cada parte y la regla de la palabra que las une. Esas reglas se escriben en tablas con todas las combinaciones posibles.",
    why: "Las tablas nos dan un método mecánico y seguro. Con ellas después vamos a decidir si un enunciado es tautología, y si un argumento es válido.",
    origin: "Las tablas recorren todas las combinaciones de V y F de las partes (2 partes → 4 filas). La de cada conectiva fija cómo la usamos: por ejemplo, el condicional se define para que solo lo falsee el caso que «rompe la promesa».",
    board: [
      { expr: "A = V, B = F" },
      { expr: "A ∧ B = F", note: "falta que B sea V" },
      { expr: "A ∨ B = V", note: "alcanza con A" },
      { expr: "A → B = F", note: "antecedente V, consecuente F" },
      { expr: "A ↔ B = F", note: "no coinciden" },
    ],
  },
};

export const ipcCondiciones: Lesson = {
  id: "l-ipc-condiciones",
  title: "Condiciones necesarias y suficientes",
  subtitle: "«Si», «solo si» y «si y solo si»",
  subjectId: S,
  topicIds: ["t-ipc-condiciones"],
  estimatedMinutes: 10,
  prerequisites: ["t-ipc-conectivas"],
  cards: [
    intro(
      "Lo que alcanza y lo que hace falta",
      "Vas a traducir oraciones con «si», «solo si» y «si y solo si» a la forma «Si A, entonces B», e identificar condiciones necesarias y suficientes.",
      "Confundir «si» con «solo si» es uno de los errores más caros del parcial, y también aparece en ciencia: una condición necesaria no garantiza el resultado.",
    ),
    explain(
      "Hace falta vs. alcanza",
      "Para votar en Argentina **hace falta** estar empadronado: es **necesario**. Pero no **alcanza** (también hay que ir a votar).\n\nSacarse un 10 en ambos parciales **alcanza** para aprobar: es **suficiente**. Pero no **hace falta** (con un 7 también aprobás).\n\nSuficiente = alcanza. Necesaria = sin eso, no hay.",
      { tag: "cotidiano" },
    ),
    quiz("Chequeo rápido", {
      id: "q-ipc-nec-1",
      subjectId: S,
      topicId: "t-ipc-condiciones",
      prompt: "«El auto arranca **solo si** tiene nafta.» ¿Qué oración dice lo mismo?",
      options: ["Si el auto tiene nafta, arranca.", "Si el auto arranca, tiene nafta.", "El auto arranca si y solo si tiene nafta.", "Basta con tener nafta para que el auto arranque."],
      answer: 1,
      explanation: "«Solo si» marca la condición NECESARIA: tener nafta. La forma es «Si arranca, tiene nafta». Las opciones 1 y 4 la tratan como suficiente (¡puede tener nafta y la batería descargada!); la 3 es un bicondicional, más fuerte.",
      hints: ["¿La nafta alcanza o hace falta?", "«A solo si B» = «Si A, B».", "Lo que va después de «solo si» va en el consecuente."],
      errors: { 0: ["logica", "Esa trata a la nafta como suficiente. «Solo si» marca condición necesaria."], 2: ["logica", "El bicondicional agrega el otro sentido; la oración original no lo afirma."], 3: ["logica", "«Basta con» = suficiente. Pero la nafta es necesaria, no suficiente."] },
    }),
    explain(
      "Tabla de traducción",
      "• «Si A, B» · «B si A» · «Basta A para B» → **Si A, entonces B**.\n• «A solo si B» · «Solo si B, A» · «Es necesario B para A» → **Si A, entonces B**.\n• «A si y solo si B» · «A siempre y cuando B» → **bicondicional**.\n\nEn «Si A, entonces B»: **A es suficiente** para B y **B es necesaria** para A.\n\nUn condicional equivale a su **contrarrecíproco** (Si no B, no A), **no** a su recíproco (Si B, A).",
      { tag: "matematico" },
    ),
    board(
      "Traducir un «solo si»",
      [
        { expr: "«Solo si hay quórum, se vota la reforma.»" },
        { expr: "Condición necesaria: hay quórum", note: "es lo que sigue a «solo si»" },
        { expr: "Si se vota la reforma, hay quórum.", note: "la necesaria va en el consecuente" },
        { expr: "V → Q", note: "V = se vota la reforma; Q = hay quórum" },
        { expr: "Falsa solo si: V = V y Q = F", note: "se vota la reforma SIN quórum" },
      ],
      "Pasamos la oración a «Si…, entonces…» y buscamos el único caso que la falsea:",
    ),
    example(
      "¿Necesaria o suficiente?",
      "«Si una figura es un cuadrado, tiene cuatro lados.» ¿Qué es «tener cuatro lados» respecto de «ser un cuadrado»?",
      ["Antecedente: es un cuadrado. Consecuente: tiene cuatro lados.", "El consecuente es condición necesaria del antecedente: sin cuatro lados no hay cuadrado.", "Pero no es suficiente: un rectángulo también tiene cuatro lados."],
      "Tener cuatro lados es condición necesaria (no suficiente) de ser un cuadrado.",
    ),
    practice("Ejercicio guiado", "ipc-nec-suf", 1, 6, true),
    explain(
      "Error típico: dar vuelta el condicional",
      "«Laura aprueba solo si estudia» **no** dice «Si Laura estudia, aprueba». Dice «Si aprueba, estudió».\n\nOtro error: creer que «solo si» es un bicondicional. El bicondicional es «**si y** solo si».\n\nTruco: el recíproco (Si B, A) **no** equivale; el contrarrecíproco (Si no B, no A) **sí**.",
      { tag: "intuitivo" },
    ),
    practice("Tu turno", "ipc-nec-suf", 3, 10),
    practice("Desafío", "ipc-nec-suf", 5, 17),
    summary([
      "Suficiente = alcanza; necesaria = sin ella no hay.",
      "«Si A, B»: A es suficiente para B; B es necesaria para A.",
      "«A solo si B» = «Si A, B». Lo que sigue a «solo si» es la condición necesaria.",
      "«Si y solo si» = bicondicional: necesaria y suficiente a la vez.",
      "Un condicional equivale a su contrarrecíproco, nunca a su recíproco.",
    ]),
  ],
  tutor: {
    normal: "En un condicional «Si A, entonces B», el antecedente es condición suficiente del consecuente y el consecuente es condición necesaria del antecedente. Las expresiones «solo si», «únicamente si» y «es necesario que» introducen la condición necesaria, que en la forma lógica ocupa el lugar del consecuente.",
    simple: "Suficiente es lo que alcanza; necesario es lo que no puede faltar. «Solo si» te marca lo que no puede faltar, y eso va después del «entonces».",
    nino: "Para entrar al recital hace falta la entrada (necesaria), pero si no llegás a horario no entrás igual. En cambio, tener pase VIP alcanza (suficiente), aunque no hace falta: con entrada común también entrás.",
    ejemplo: "«Solo si hay quórum, se vota» = «Si se vota, hay quórum». Lo único que la vuelve falsa: que se vote sin quórum.",
    fromZero: "Un condicional une dos enunciados: el de después de «si» (antecedente) y el otro (consecuente). Dice que siempre que pasa el antecedente, pasa el consecuente. Entonces el antecedente alcanza para el consecuente (suficiente), y el consecuente no puede faltar cuando hay antecedente (necesario). «Solo si» cambia de lugar las piezas: lo que viene después de él es lo que no puede faltar.",
    why: "Muchísimos razonamientos, cotidianos y científicos, dependen de no confundir «hace falta» con «alcanza». Confundirlos lleva directo a las falacias formales de la próxima lección.",
    origin: "Sale de la tabla del condicional: «Si A, B» solo es falso con A V y B F. Entonces nunca pasa A sin B (A alcanza para B) y nunca hay A si falta B (B es necesaria). El contrarrecíproco tiene exactamente la misma tabla; el recíproco no.",
    board: [
      { expr: "«A solo si B»" },
      { expr: "A → B", note: "B es necesaria para A" },
      { expr: "¬B → ¬A", note: "contrarrecíproco: equivalente" },
      { expr: "B → A", note: "recíproco: NO equivalente" },
    ],
  },
};

export const ipcTautologias: Lesson = {
  id: "l-ipc-tautologias",
  title: "Tautologías, contradicciones y contingencias",
  subtitle: "Verdad por la forma o por el mundo",
  subjectId: S,
  topicIds: ["t-ipc-tautologias"],
  estimatedMinutes: 9,
  prerequisites: ["t-ipc-conectivas"],
  cards: [
    intro(
      "Algunas oraciones no dicen nada del mundo",
      "Vas a clasificar enunciados en tautologías, contradicciones y contingencias usando tablas de verdad.",
      "Es un ítem fijo del parcial («completá para que sea tautología…») y prepara una idea clave de Popper: un enunciado que no puede ser falso no informa nada sobre el mundo.",
    ),
    explain(
      "El pronóstico infalible",
      "«Mañana llueve o no llueve.» Nunca falla… porque no dice nada: es verdadera **por su forma**. Es una **tautología**.\n\n«Mañana llueve y no llueve» es falsa por su forma: **contradicción**.\n\n«Mañana llueve» puede ser V o F según cómo esté el mundo: **contingencia**.",
      { tag: "intuitivo" },
    ),
    quiz("Chequeo rápido", {
      id: "q-ipc-tau-1",
      subjectId: S,
      topicId: "t-ipc-tautologias",
      prompt: "«Buenos Aires es la capital de la Argentina.» ¿Qué tipo de enunciado es?",
      options: ["Tautología", "Contradicción", "Contingencia"],
      answer: 2,
      explanation: "Es verdadero, pero por cómo es el mundo, no por su forma: podría haber sido falso (la capital pudo haber sido otra). Por eso es contingente.",
      hints: ["¿Es verdadero solo por su forma?", "Imaginá un mundo distinto: ¿podría ser falso?", "Obviamente verdadero no es lo mismo que tautología."],
      errors: { 0: ["logica", "Que sea obviamente verdadero no lo vuelve tautología: su verdad depende de los hechos, no de la forma."], 1: ["logica", "No es falso en todos los casos: de hecho es verdadero."] },
    }),
    explain(
      "Cómo decidirlo con la tabla",
      "Armá la tabla con todas las combinaciones de V y F de las letras:\n\n• **Todas V** → tautología.\n• **Todas F** → contradicción.\n• **De las dos** → contingencia.\n\nAtajos: tautología **o** cualquier cosa = tautología. Tautología **y** contingencia = contingencia. Contradicción **o** contingencia = contingencia. La negación de una tautología es contradicción, y viceversa.",
      { tag: "matematico" },
    ),
    board(
      "Tabla de «Si A y B, entonces A»",
      [
        { expr: "A = V, B = V → V ∧ V = V → (V → V) = V" },
        { expr: "A = V, B = F → V ∧ F = F → (F → V) = V", note: "antecedente falso: condicional verdadero" },
        { expr: "A = F, B = V → F ∧ V = F → (F → F) = V" },
        { expr: "A = F, B = F → F ∧ F = F → (F → F) = V" },
        { expr: "Todas V → tautología", note: "es verdadera por su forma" },
      ],
      "Recorremos las cuatro filas de (A ∧ B) → A:",
    ),
    example(
      "Completar la oración",
      "«El cuarzo es duro…» Elegí la continuación que la vuelve contradicción: (a) «o no es duro», (b) «pero no es duro», (c) «y es transparente».",
      ["(a) «A o no A»: tautología.", "(b) «A pero no A» = «A y no A»: contradicción («pero» es «y»).", "(c) «A y C»: contingencia (agrega contenido nuevo)."],
      "La (b) la vuelve contradicción.",
    ),
    practice("Ejercicio guiado", "ipc-tautologia", 1, 2, true),
    explain(
      "Errores típicos",
      "• Creer que todo lo **verdadero conocido** es tautología. «El agua hierve a 100 °C a nivel del mar» es contingente.\n• Pensar que «pero no» da algo distinto de «y no»: también es contradicción.\n• Clasificar sin mirar **todas** las filas: una sola F ya descarta la tautología, y una sola V descarta la contradicción.",
      { tag: "intuitivo" },
    ),
    practice("Tu turno", "ipc-tautologia", 3, 11),
    practice("Desafío", "ipc-tautologia", 5, 15),
    summary([
      "Tautología: V en todas las filas, por su forma.",
      "Contradicción: F en todas las filas, por su forma.",
      "Contingencia: su verdad depende de cómo es el mundo (aunque sea obviamente verdadera).",
      "«A o no A» es tautología; «A y no A» (o «A pero no A») es contradicción.",
      "Decidilo con la tabla completa de verdad.",
    ]),
  ],
  tutor: {
    normal: "Una tautología es un enunciado verdadero bajo toda asignación de valores de verdad a sus componentes; una contradicción, falso bajo toda asignación; una contingencia, verdadero bajo algunas y falso bajo otras. La clasificación depende exclusivamente de la forma lógica.",
    simple: "Si no hay manera de que sea falso, es tautología. Si no hay manera de que sea verdadero, es contradicción. Si depende de lo que pase en el mundo, es contingencia.",
    nino: "Un horóscopo que dice «hoy te va a pasar algo o no te va a pasar nada» nunca se equivoca… pero tampoco te sirve para nada. Eso es una tautología.",
    ejemplo: "«Si llueve, llueve» es tautología. «Llueve y no llueve» es contradicción. «Si llueve, hay barro» es contingencia.",
    fromZero: "Un enunciado complejo combina letras (A, B…) con conectivas. Cada letra puede ser V o F. Si probamos todas las combinaciones posibles y anotamos el resultado, obtenemos la tabla de verdad. Mirando la última columna sabemos si el enunciado sale siempre V, siempre F o a veces cada cosa.",
    why: "Distinguir verdad por forma de verdad por hechos es central en filosofía de la ciencia: las tautologías no pueden ser refutadas por ninguna observación, y por eso no son conocimiento empírico.",
    origin: "Surge directamente de las tablas de las conectivas: como el valor del complejo depende solo de los valores de las partes, basta recorrer todas las combinaciones (2ⁿ filas para n letras) para saber si existe alguna fila V o alguna fila F.",
    board: [
      { expr: "A ∨ ¬A: V ∨ F = V; F ∨ V = V", note: "siempre V → tautología" },
      { expr: "A ∧ ¬A: V ∧ F = F; F ∧ V = F", note: "siempre F → contradicción" },
      { expr: "A ∧ B: V solo en V-V", note: "a veces V → contingencia" },
    ],
  },
};

export const ipcValidez: Lesson = {
  id: "l-ipc-validez",
  title: "Validez, verdad y solidez",
  subtitle: "Los argumentos deductivos y la preservación de la verdad",
  subjectId: S,
  topicIds: ["t-ipc-validez"],
  estimatedMinutes: 10,
  prerequisites: ["t-ipc-argumentos", "t-ipc-conectivas"],
  cards: [
    intro(
      "Bien razonado no es lo mismo que verdadero",
      "Vas a distinguir la validez de un argumento de la verdad de sus premisas y conclusión, y a reconocer los argumentos sólidos.",
      "Las preguntas «Si un argumento es válido, entonces…» aparecen en todos los parciales, y casi siempre los errores vienen de mezclar los planos de la verdad y la forma.",
    ),
    explain(
      "Una máquina que no falla",
      "Pensá un argumento deductivo válido como una máquina: si le ponés **verdades** en la entrada, **nunca** te devuelve una falsedad.\n\nPero si le ponés algo falso, puede salir cualquier cosa. La máquina no controla qué le das: solo garantiza el paso.\n\nEso es la **validez**: preservar la verdad, por la **forma**.",
      { tag: "intuitivo" },
    ),
    quiz("Chequeo rápido", {
      id: "q-ipc-val-1",
      subjectId: S,
      topicId: "t-ipc-validez",
      prompt: "Un argumento válido tiene **conclusión falsa**. ¿Qué se puede afirmar?",
      options: ["Que al menos una premisa es falsa.", "Que todas las premisas son falsas.", "Que en realidad es inválido.", "Nada sobre las premisas."],
      answer: 0,
      explanation: "Si todas las premisas fueran verdaderas, por ser válido la conclusión tendría que ser verdadera. Como es falsa, alguna premisa es falsa (no necesariamente todas).",
      hints: ["Recordá: válido = imposible premisas V y conclusión F.", "Si todas las premisas fueran V, ¿qué pasaría con la conclusión?", "Falsa es la conjunción de las premisas, no cada una."],
      errors: { 1: ["logica", "Alcanza con que una sea falsa: lo falso es la conjunción de las premisas, no necesariamente cada una."], 2: ["logica", "Un argumento válido puede tener conclusión falsa si alguna premisa es falsa."], 3: ["logica", "Sí se puede: alguna premisa tiene que ser falsa."] },
    }),
    explain(
      "Definiciones",
      "• **Válido**: es **imposible** que las premisas sean V y la conclusión F. Depende solo de la **forma**.\n• **Inválido**: hay al menos un caso (**contraejemplo**) con premisas V y conclusión F.\n• **Sólido**: válido **y** con premisas verdaderas. Su conclusión es V.\n\nEn un argumento válido valen las combinaciones V/V, F/V y F/F (premisas/conclusión). Solo **V/F** está prohibida.\n\n«Válido» se dice de **argumentos**; «verdadero», de **enunciados**.",
      { tag: "matematico" },
    ),
    board(
      "Probar la invalidez con un contraejemplo",
      [
        { expr: "Si A, B. B. Por lo tanto, A.", note: "la forma que queremos evaluar" },
        { expr: "A: «Rosario está en Chile»", note: "elegimos un antecedente FALSO…" },
        { expr: "B: «Rosario está en América»", note: "…y un consecuente VERDADERO" },
        { expr: "P1: Si Rosario está en Chile, está en América. (V)", note: "antecedente F → condicional V" },
        { expr: "P2: Rosario está en América. (V)" },
        { expr: "C: Rosario está en Chile. (F)", note: "premisas V y conclusión F" },
        { expr: "La forma es inválida", note: "encontramos un contraejemplo" },
      ],
      "Un solo contraejemplo alcanza para mostrar que una forma es inválida:",
    ),
    example(
      "Todo verdadero e igual inválido",
      "«Si Córdoba está en Argentina, está en América. Córdoba está en América. Por lo tanto, Córdoba está en Argentina.» ¿Es válido?",
      ["Las dos premisas y la conclusión son verdaderas.", "Pero la forma es «Si A, B; B; ∴ A».", "Esa forma admite contraejemplos (como el de Rosario y Chile).", "La verdad de las oraciones no decide la validez."],
      "Es inválido, aunque todo lo que dice sea verdadero.",
    ),
    practice("Ejercicio guiado", "ipc-validez-verdad", 1, 3, true),
    explain(
      "Errores clásicos",
      "• «Premisas y conclusión verdaderas → válido.» Falso: puede ser inválido.\n• «Inválido → conclusión falsa.» Falso: puede tener conclusión verdadera.\n• «Las premisas son válidas.» No: las oraciones son V o F.\n• «Válido → sólido.» Falso: puede tener premisas falsas. Al revés sí: todo sólido es válido.",
      { tag: "intuitivo" },
    ),
    practice("Tu turno", "ipc-validez-verdad", 3, 6),
    practice("Desafío", "ipc-validez-verdad", 5, 10),
    summary([
      "Válido: imposible premisas V y conclusión F. Depende solo de la forma.",
      "Un válido puede tener premisas falsas; un inválido puede tener todo verdadero.",
      "Sólido = válido + premisas verdaderas → conclusión verdadera.",
      "Un contraejemplo (premisas V, conclusión F) prueba que la forma es inválida.",
      "Validez para argumentos; verdad para enunciados.",
    ]),
  ],
  tutor: {
    normal: "Un argumento deductivo es válido cuando no hay ninguna interpretación en que sus premisas sean verdaderas y su conclusión falsa: la validez preserva la verdad y depende solo de la forma lógica. Un argumento sólido es un argumento válido con premisas verdaderas, por lo que su conclusión es verdadera.",
    simple: "Válido quiere decir que, si las premisas fueran ciertas, la conclusión también lo sería sí o sí. No dice que las premisas sean ciertas. Cuando además lo son, el argumento es sólido.",
    nino: "Es como una receta perfecta: si usás ingredientes buenos, la torta sale bien seguro. Si usás huevos podridos, la receta no tiene la culpa de que salga mal… y a veces, de casualidad, igual sale rica.",
    ejemplo: "«Todos los peces vuelan. La trucha es un pez. ∴ La trucha vuela.» Es válido (forma correcta) pero no sólido (la primera premisa es falsa).",
    fromZero: "Un argumento tiene premisas y una conclusión, y cada uno de esos enunciados es V o F. La validez no pregunta si son V o F en la realidad: pregunta si la forma del argumento garantiza que, cuando las premisas son V, la conclusión también lo sea. Si existe aunque sea un caso con premisas V y conclusión F, la forma no lo garantiza.",
    why: "Separar forma y contenido nos permite evaluar razonamientos sin saber de todo. Para saber si alguien razona bien no necesito saber si sus datos son ciertos; para saber si su conclusión es confiable, necesito las dos cosas.",
    origin: "La definición sale de pensar qué le pedimos a una deducción: que no nos haga pasar de verdades a una falsedad. Por eso la única combinación prohibida es premisas V con conclusión F, y por eso un solo contraejemplo alcanza para mostrar invalidez.",
    board: [
      { expr: "Premisas V, conclusión V → puede ser válido" },
      { expr: "Premisas F, conclusión V → puede ser válido" },
      { expr: "Premisas F, conclusión F → puede ser válido" },
      { expr: "Premisas V, conclusión F → nunca válido", note: "es un contraejemplo" },
    ],
  },
};

export const ipcFormas: Lesson = {
  id: "l-ipc-formas",
  title: "Formas válidas y falacias formales",
  subtitle: "Modus ponens, modus tollens y sus impostores",
  subjectId: S,
  topicIds: ["t-ipc-formas"],
  estimatedMinutes: 11,
  prerequisites: ["t-ipc-validez", "t-ipc-condiciones"],
  cards: [
    intro(
      "Las formas que hay que reconocer a simple vista",
      "Vas a reconocer las formas válidas (modus ponens, modus tollens, silogismo hipotético, silogismo disyuntivo…) y las dos falacias formales del programa.",
      "En el parcial te piden «¿cuál es válido?». Y en la Unidad 3 vas a ver que refutar una hipótesis es un modus tollens, mientras que «confirmarla» es una falacia.",
    ),
    explain(
      "Dos maneras correctas de usar un «si»",
      "«Si se corta la luz, se apaga la heladera.»\n\n• **Se cortó la luz** → la heladera se apagó. (Afirmo el antecedente: **modus ponens**.)\n• **La heladera no se apagó** → no se cortó la luz. (Niego el consecuente: **modus tollens**.)\n\nPero si la heladera está apagada, ¿se cortó la luz? No necesariamente: ¡tal vez la desenchufaron!",
      { tag: "cotidiano" },
    ),
    quiz("Chequeo rápido", {
      id: "q-ipc-for-1",
      subjectId: S,
      topicId: "t-ipc-formas",
      prompt: "«Si el agua del lago se congela, la temperatura bajó de 0 °C. La temperatura no bajó de 0 °C. Por lo tanto, el agua del lago no se congeló.» Este argumento:",
      options: ["es válido, porque tiene la forma de modus tollens.", "es inválido: es una negación del antecedente.", "es válido solo si sus premisas son verdaderas.", "es inválido, porque su conclusión podría ser falsa."],
      answer: 0,
      explanation: "La forma es «Si A, B; no B; ∴ no A»: modus tollens, válido. La validez no depende de que las premisas sean verdaderas (eso sería solidez).",
      hints: ["Esquematizá: A = el agua se congela; B = la temperatura bajó de 0 °C.", "¿Se niega el antecedente o el consecuente?", "Negar el consecuente y concluir la negación del antecedente es modus tollens."],
      errors: { 1: ["logica", "Acá se niega el CONSECUENTE (B), no el antecedente: es modus tollens."], 2: ["logica", "Eso confunde validez con solidez: la validez depende solo de la forma."], 3: ["logica", "Cualquier conclusión «podría ser falsa» si las premisas lo son; eso no hace inválido a un argumento."] },
    }),
    explain(
      "El catálogo",
      "**Válidas:**\n• Modus ponens: Si A, B; A; ∴ B.\n• Modus tollens: Si A, B; no B; ∴ no A.\n• Silogismo hipotético: Si A, B; si B, C; ∴ si A, C.\n• Silogismo disyuntivo: A o B; no A; ∴ B.\n\n**Falacias formales (inválidas):**\n• Afirmación del consecuente: Si A, B; B; ∴ A.\n• Negación del antecedente: Si A, B; no A; ∴ no B.",
      { tag: "matematico" },
    ),
    board(
      "Esquematizar y comparar",
      [
        { expr: "«Si la planta recibe luz, hace fotosíntesis. La planta no recibe luz. Luego, no hace fotosíntesis.»" },
        { expr: "A = la planta recibe luz; B = hace fotosíntesis", note: "una letra por oración simple" },
        { expr: "A → B, ¬A ∴ ¬B", note: "se niega el ANTECEDENTE" },
        { expr: "Negación del antecedente", note: "comparamos con el catálogo" },
        { expr: "A = F, B = V: premisas V, conclusión F", note: "contraejemplo: B puede ocurrir por otra causa" },
        { expr: "Inválido" },
      ],
      "El procedimiento de siempre: letras, esquema, catálogo, y si hace falta, contraejemplo.",
    ),
    example(
      "Una afirmación del consecuente",
      "«Si un animal es un perro, es un mamífero. Mi gato es un mamífero. Por lo tanto, mi gato es un perro.»",
      ["A = es un perro; B = es un mamífero.", "Forma: Si A, B; B; ∴ A.", "Es la falacia de afirmación del consecuente.", "Contraejemplo real: las premisas son V y la conclusión, F."],
      "Inválido: afirmación del consecuente.",
    ),
    practice("Ejercicio guiado", "ipc-forma-argumento", 1, 4, true),
    explain(
      "La confusión más cara",
      "Muchos resúmenes definen mal el modus tollens como «Si A, B; B; ∴ A». **Eso es la falacia de afirmación del consecuente.**\n\nRegla para no fallar:\n• Afirmar el **antecedente** → válido (MP).\n• Negar el **consecuente** → válido (MT).\n• Afirmar el **consecuente** o negar el **antecedente** → falacia.\n\nY recordá: si te dan «A solo si B», primero pasalo a «Si A, B».",
      { tag: "intuitivo" },
    ),
    practice("Tu turno", "ipc-forma-argumento", 3, 9),
    practice("¿Cuál es válido?", "ipc-cual-valido", 3, 5),
    practice("Desafío", "ipc-forma-argumento", 6, 21),
    summary([
      "Válidas: modus ponens, modus tollens, silogismo hipotético, silogismo disyuntivo (y simplificación, adjunción, instanciación del universal).",
      "Falacias formales: afirmación del consecuente y negación del antecedente.",
      "MT = Si A, B; no B; ∴ no A. Lo otro («B ∴ A») es una falacia.",
      "Método: letras → esquema → catálogo → contraejemplo si hace falta.",
      "La verdad de las oraciones no cambia la validez de la forma.",
    ]),
  ],
  tutor: {
    normal: "Una forma de argumento es válida si toda instancia suya con premisas verdaderas tiene conclusión verdadera. El modus ponens afirma el antecedente; el modus tollens niega el consecuente. La afirmación del consecuente y la negación del antecedente son falacias formales: formas inválidas que se parecen a las válidas.",
    simple: "Con un «si A, B» podés concluir B cuando sabés A, y podés concluir «no A» cuando sabés «no B». Lo demás es trampa: saber B no te dice nada seguro sobre A.",
    nino: "«Si llueve, el patio está mojado.» Si ves el patio seco, seguro no llovió. Pero si lo ves mojado, a lo mejor alguien regó: no podés asegurar que llovió.",
    ejemplo: "«Si es un triángulo, tiene tres lados. Esta figura no tiene tres lados. ∴ No es un triángulo.» Modus tollens: válido.",
    fromZero: "Un condicional tiene dos partes: antecedente (después del «si») y consecuente. Con la segunda premisa podés afirmar o negar alguna de esas partes: son cuatro posibilidades. Dos de ellas garantizan la conclusión (afirmar el antecedente, negar el consecuente) y dos no (afirmar el consecuente, negar el antecedente).",
    why: "Reconocer formas te deja evaluar muchos argumentos a la vez sin pensar caso por caso. Además, estas mismas formas explican por qué en ciencia una predicción fallida refuta, pero una predicción cumplida no prueba.",
    origin: "Se deduce de la tabla del condicional. Si A → B es V y A es V, la única fila posible tiene B = V (MP). Si A → B es V y B es F, la única fila posible tiene A = F (MT). En cambio, con A → B V y B V quedan dos filas, una con A = F: por eso concluir A es inválido.",
    board: [
      { expr: "A → B, A ∴ B", note: "modus ponens: válido" },
      { expr: "A → B, ¬B ∴ ¬A", note: "modus tollens: válido" },
      { expr: "A → B, B ∴ A", note: "afirmación del consecuente: inválido" },
      { expr: "A → B, ¬A ∴ ¬B", note: "negación del antecedente: inválido" },
    ],
  },
};

export const ipcPruebas: Lesson = {
  id: "l-ipc-pruebas",
  title: "Reglas de inferencia y pruebas",
  subtitle: "Pruebas directas e indirectas",
  subjectId: S,
  topicIds: ["t-ipc-pruebas"],
  estimatedMinutes: 10,
  prerequisites: ["t-ipc-formas"],
  cards: [
    intro(
      "Encadenar pasos seguros",
      "Vas a usar las reglas de inferencia para justificar cada paso de una prueba directa, y a armar una prueba indirecta (por el absurdo).",
      "Una prueba muestra que una conclusión se sigue de las premisas aunque el argumento sea largo: cada paso es pequeño y seguro, y el resultado hereda esa seguridad.",
    ),
    explain(
      "Como subir una escalera",
      "No hace falta saltar de las premisas a la conclusión de golpe. Se puede subir de a un escalón: cada línea nueva se obtiene de líneas anteriores con una **regla de inferencia** válida.\n\nSi cada escalón es firme, llegar arriba es seguro.",
      { tag: "intuitivo" },
    ),
    quiz("Chequeo rápido", {
      id: "q-ipc-pru-1",
      subjectId: S,
      topicId: "t-ipc-pruebas",
      prompt: "De la línea «La muestra está contaminada y el cultivo da positivo» se obtiene «El cultivo da positivo». ¿Qué regla se usó?",
      options: ["Simplificación", "Adjunción", "Modus ponens", "Silogismo disyuntivo"],
      answer: 0,
      explanation: "De una conjunción se puede obtener cualquiera de sus partes: simplificación. La adjunción hace lo inverso (une dos líneas en una conjunción).",
      hints: ["¿Qué conectiva tiene la línea de partida?", "Se pasa de algo más largo a una parte.", "A y B ∴ B."],
      errors: { 1: ["logica", "La adjunción une dos líneas en una conjunción; acá se separa una parte: simplificación."], 2: ["logica", "No hay ningún condicional en juego."], 3: ["logica", "No hay disyunción («o») en la línea de partida."] },
    }),
    explain(
      "Las reglas del programa",
      "• **MP**: Si A, B; A ∴ B.\n• **MT**: Si A, B; no B ∴ no A.\n• **SH**: Si A, B; si B, C ∴ si A, C.\n• **SD**: A o B; no A ∴ B.\n• **Simp**: A y B ∴ A (o B).\n• **Adj**: A; B ∴ A y B.\n• **IU**: Todos los R son P; x es R ∴ x es P.\n\n**Prueba directa**: cada línea es premisa o sale de anteriores.\n**Indirecta**: se supone lo contrario, se llega a una contradicción y se rechaza el supuesto.",
      { tag: "matematico" },
    ),
    board(
      "Prueba directa",
      [
        { expr: "1. Si llueve, el partido se suspende.", note: "premisa" },
        { expr: "2. Si el partido se suspende, el club devuelve las entradas.", note: "premisa" },
        { expr: "3. Llueve.", note: "premisa" },
        { expr: "4. El partido se suspende.", note: "MP 1, 3" },
        { expr: "5. El club devuelve las entradas.", note: "MP 2, 4" },
      ],
      "Queremos probar «El club devuelve las entradas»:",
      "Otra opción: SH entre 1 y 2 («Si llueve, el club devuelve las entradas») y después MP con 3.",
    ),
    example(
      "Prueba indirecta (por el absurdo)",
      "Premisas: (1) Si el examen es oral, Juan se pone nervioso. (2) Si el examen es oral, Juan no se pone nervioso. Probar: el examen no es oral.",
      ["3. Supuesto: el examen es oral (lo contrario de lo que queremos).", "4. Juan se pone nervioso (MP 1, 3).", "5. Juan no se pone nervioso (MP 2, 3).", "6. Juan se pone nervioso y no se pone nervioso (Adj 4, 5): contradicción.", "7. Se rechaza el supuesto."],
      "El examen no es oral.",
    ),
    practice("Ejercicio guiado", "ipc-regla-inferencia", 1, 2, true),
    explain(
      "Errores típicos",
      "• Llamar «adición» a «A; B ∴ A y B»: es **adjunción**.\n• Citar mal las líneas: MP necesita el condicional **y** su antecedente.\n• Usar el SD sin la negación: «A o B ∴ B» es inválido.\n• En la prueba indirecta, olvidar que el supuesto es **provisional**: al final se lo rechaza.",
      { tag: "intuitivo" },
    ),
    practice("Tu turno", "ipc-regla-inferencia", 3, 8),
    practice("Desafío", "ipc-regla-inferencia", 5, 16),
    summary([
      "Reglas: MP, MT, SH, SD, Simplificación, Adjunción, Instanciación del universal.",
      "Prueba directa: cada línea es premisa o sale de anteriores por una regla.",
      "Prueba indirecta: supuesto contrario → contradicción → se rechaza el supuesto.",
      "Justificá cada paso con la regla y los números de línea.",
    ]),
  ],
  tutor: {
    normal: "Una prueba (o deducción) es una secuencia finita de enunciados en la que cada uno es una premisa o se obtiene de enunciados anteriores mediante una regla de inferencia válida. En la prueba indirecta se introduce como supuesto la negación de lo que se quiere probar, se deriva una contradicción y se concluye la negación del supuesto.",
    simple: "Probar es ir de las premisas a la conclusión con pasitos seguros, diciendo en cada uno qué regla usaste. Si no te sale directo, suponé lo contrario y mostrá que termina en un absurdo.",
    nino: "Es como un detective: «Si el ladrón entró por la ventana, habría barro. No hay barro. Entonces no entró por la ventana». Cada pista lleva a la siguiente.",
    ejemplo: "1. A y B (premisa). 2. Si A, C (premisa). 3. A (Simp 1). 4. C (MP 2, 3).",
    fromZero: "Las reglas de inferencia son formas válidas cortitas, como modus ponens. Una prueba es una lista numerada: primero escribís las premisas; después agregás líneas nuevas, cada una justificada por una regla aplicada a líneas anteriores. Cuando aparece la conclusión, terminaste.",
    why: "Algunos argumentos son demasiado largos para ver su validez de un vistazo o con una tabla enorme. La prueba la muestra paso a paso, y cada paso se puede controlar.",
    origin: "Como cada regla es una forma válida, preserva la verdad. Si todas las líneas preservan la verdad, la última también es verdadera cuando las premisas lo son. La prueba indirecta funciona porque de premisas verdaderas no puede seguirse una contradicción: si aparece, el supuesto era falso.",
    board: [
      { expr: "1. A ∧ B", note: "premisa" },
      { expr: "2. A → C", note: "premisa" },
      { expr: "3. A", note: "Simp 1" },
      { expr: "4. C", note: "MP 2, 3" },
    ],
  },
};

export const ipcInductivos: Lesson = {
  id: "l-ipc-inductivos",
  title: "Argumentos inductivos",
  subtitle: "Analogía, enumeración incompleta y silogismo inductivo",
  subjectId: S,
  topicIds: ["t-ipc-inductivos"],
  estimatedMinutes: 11,
  prerequisites: ["t-ipc-validez"],
  cards: [
    intro(
      "Ir más allá de lo que sabemos",
      "Vas a reconocer los tres tipos de argumentos inductivos del programa y a evaluarlos con sus criterios de fortaleza.",
      "Casi todo lo que creemos sobre el futuro se apoya en inducciones. En el parcial hay ítems de «completá para que sea analogía» y de «¿qué premisa lo fortalece?».",
    ),
    explain(
      "Razonar desde la experiencia",
      "Probaste tres alfajores de una marca y todos eran secos: concluís que **todos** lo son. Tu amiga usa la misma notebook que vos y le anda lenta: suponés que a vos te va a pasar lo mismo.\n\nNo es seguro, pero es razonable. Los **inductivos** pretenden que la conclusión sea **probable**, no necesaria: siempre podrían tener premisas V y conclusión F.",
      { tag: "cotidiano" },
    ),
    quiz("Chequeo rápido", {
      id: "q-ipc-ind-1",
      subjectId: S,
      topicId: "t-ipc-inductivos",
      prompt: "Desde el punto de vista deductivo, todo argumento inductivo es…",
      options: ["inválido, y se lo evalúa por su fuerza.", "válido, si sus premisas son verdaderas.", "sólido, si tiene muchos casos.", "una falacia que hay que evitar."],
      answer: 0,
      explanation: "En un inductivo la conclusión va más allá de las premisas: siempre es posible que sean V y la conclusión F. Por eso se los evalúa por grados de fuerza, no por validez. No son falacias: son otra clase de argumento.",
      hints: ["¿Puede un inductivo tener premisas V y conclusión F?", "La validez no admite grados; la fuerza sí.", "Ser inválido deductivamente no lo vuelve un mal argumento."],
      errors: { 1: ["logica", "La verdad de las premisas no da validez; además, en un inductivo siempre cabe que la conclusión sea falsa."], 2: ["logica", "«Sólido» exige validez. Los inductivos se dicen más fuertes o más débiles."], 3: ["conceptual", "No son falacias: son razonamientos no concluyentes que pueden ser fuertes."] },
    }),
    explain(
      "Los tres tipos y sus criterios",
      "• **Enumeración incompleta**: x₁ es Z; x₂ es Z… ∴ **todos** los X son Z. Criterios: **cantidad** de casos y **representatividad** de la muestra.\n• **Silogismo inductivo**: el n% de los F son G; x es F ∴ x es G. Criterios: **frecuencia** alta (sin llegar al 100%) y **evidencia total** disponible.\n• **Analogía**: x₁ y x₂ tienen F, G y Z; xₙ tiene F y G ∴ xₙ tiene Z. Criterios: **relevancia** de las semejanzas, **cantidad de aspectos** y **cantidad de casos** comparados.",
      { tag: "matematico" },
    ),
    board(
      "Reconocer el tipo",
      [
        { expr: "¿La conclusión dice «todos»?", note: "→ enumeración incompleta" },
        { expr: "¿Conclusión singular + premisa con «el n%» o «la mayoría»?", note: "→ silogismo inductivo" },
        { expr: "¿Conclusión singular por semejanza con otros casos?", note: "→ analogía" },
        { expr: "¿Una premisa dice «todos» o «son los únicos»?", note: "→ ya no es inductivo: es deductivo" },
      ],
      "Empezá siempre por la conclusión:",
    ),
    example(
      "Fortalecer una enumeración",
      "«La planta 1 es del invernadero y dio frutos en enero. La planta 2 es del invernadero y dio frutos en enero. Por lo tanto, todas las plantas del invernadero dieron frutos en enero.» ¿Qué agregado la fortalece?",
      ["Es una enumeración incompleta: generaliza a «todas».", "Se fortalece con más casos COMPLETOS (que sean del invernadero y hayan dado frutos).", "«La planta 3 dio frutos» está incompleto: no dice que sea del invernadero.", "«Estas son las únicas plantas» la vuelve deductiva: cambia el tipo."],
      "Agregar: «La planta 3 es del invernadero y dio frutos en enero».",
    ),
    practice("Ejercicio guiado", "ipc-tipo-inductivo", 1, 3, true),
    explain(
      "Trampas frecuentes",
      "• Agregar un caso **incompleto** no suma evidencia.\n• Agregar «estos son los **únicos** casos» convierte la enumeración en completa: **deductiva**.\n• En un silogismo inductivo, subir al **100%** («todos») lo vuelve instanciación del universal: deductivo.\n• En una analogía, agregar una premisa con porcentaje o con «todos» cambia el tipo.\n• Las semejanzas **irrelevantes** (el color del collar de un perro) no fortalecen una analogía.",
      { tag: "intuitivo" },
    ),
    practice("Tu turno", "ipc-tipo-inductivo", 4, 9),
    practice("Fortalecer", "ipc-fortalecer-inductivo", 3, 7),
    practice("Desafío", "ipc-fortalecer-inductivo", 5, 18),
    summary([
      "Los inductivos son deductivamente inválidos y se evalúan por su fuerza (cuestión de grado).",
      "Enumeración incompleta → «todos»; criterios: cantidad y representatividad.",
      "Silogismo inductivo → porcentaje + caso; criterios: frecuencia alta (< 100%) y evidencia total.",
      "Analogía → semejanzas; criterios: relevancia, cantidad de aspectos y de casos.",
      "Fortalecer sin cambiar el tipo: nada de «todos», «los únicos» ni 100%.",
    ]),
  ],
  tutor: {
    normal: "Los argumentos inductivos pretenden que sus premisas hagan probable la conclusión. Son deductivamente inválidos y se evalúan por su fuerza, que depende de criterios propios de cada tipo: cantidad y representatividad en la enumeración incompleta; frecuencia relativa y evidencia total en el silogismo inductivo; relevancia, cantidad de aspectos y de casos en la analogía.",
    simple: "Inducir es sacar una conclusión probable a partir de casos. Nunca es segura, pero puede ser más o menos fuerte: más casos, casos variados, porcentajes altos y semejanzas que importan la hacen más fuerte.",
    nino: "Si los últimos cinco viernes hubo milanesas en el comedor, apostás a que este viernes también. Puede fallar, pero es una buena apuesta.",
    ejemplo: "«El 90% de los estudiantes que hacen todas las autoevaluaciones aprueba. Rocío las hizo todas. ∴ Rocío aprobará.» Silogismo inductivo; con 95% sería más fuerte; con «todos» dejaría de ser inductivo.",
    fromZero: "Un argumento deductivo válido garantiza su conclusión. Pero muchas veces razonamos a partir de casos observados para hablar de casos no observados: eso es inducir. Como la conclusión dice más que las premisas, siempre podría fallar. Entonces, en vez de preguntar «¿es válido?», preguntamos «¿qué tan fuerte es?».",
    why: "La ciencia y la vida diaria necesitan generalizar y anticipar. Saber qué hace fuerte o débil una inducción te protege de generalizaciones apresuradas y de comparaciones engañosas.",
    origin: "Los criterios salen de preguntarse qué hace menos probable que la conclusión falle: más casos reducen la casualidad, muestras variadas reducen el sesgo, porcentajes altos acercan al «casi siempre», y semejanzas relevantes conectan de verdad los casos comparados.",
    board: [
      { expr: "x₁ es Z, x₂ es Z ∴ todos los X son Z", note: "enumeración incompleta" },
      { expr: "n% de F son G, x es F ∴ x es G", note: "silogismo inductivo (n < 100)" },
      { expr: "x₁, x₂: F, G, Z; xₙ: F, G ∴ xₙ: Z", note: "analogía" },
    ],
  },
};

const U1_LESSONS: Lesson[] = [ipcArgumentos, ipcEnunciados, ipcConectivas, ipcCondiciones, ipcTautologias, ipcValidez, ipcFormas, ipcPruebas, ipcInductivos];

// ═══════════════════════ Unidad 2 · La revolución darwiniana ═══════════════════════

export const ipcPreDarwin: Lesson = {
  id: "l-ipc-pre-darwin",
  title: "Antes de Darwin",
  subtitle: "Creacionismo, fijismo, Lamarck y las influencias de Darwin",
  subjectId: S,
  topicIds: ["t-ipc-pre-darwin"],
  estimatedMinutes: 10,
  prerequisites: [],
  cards: [
    intro(
      "¿Por qué los seres vivos encajan con su ambiente?",
      "Vas a conocer las respuestas previas a Darwin (creacionismo, fijismo, el evolucionismo de Lamarck) y las ideas que Darwin tomó de Lyell, Malthus y los criadores.",
      "La revolución darwiniana es el caso histórico de la materia: entender contra qué discutía Darwin es la mejor forma de entender qué propuso.",
    ),
    explain(
      "Dos preguntas sobre cada rasgo",
      "El pico del carpintero, el camuflaje del camaleón, el cuello de la jirafa. Ante cada rasgo podemos preguntar: **¿qué función cumple?** y **¿cómo llegó el organismo a tenerlo?**\n\nUna respuesta tentadora es **teleológica**: explica algo presente por un **fin** («tiene el cuello largo **para** comer hojas altas»). Funciona para acciones humanas y artefactos, pero en la naturaleza parece que algo futuro causara algo presente.",
      { tag: "cotidiano" },
    ),
    quiz("Chequeo rápido", {
      id: "q-ipc-pre-1",
      subjectId: S,
      topicId: "t-ipc-pre-darwin",
      prompt: "¿Cuál de estas es una explicación **teleológica**?",
      options: [
        "El colibrí tiene el pico largo con el propósito de alcanzar el néctar de las flores tubulares.",
        "El colibrí tiene el pico largo porque sus ancestros de pico más largo comían más y dejaban más crías.",
        "El colibrí tiene el pico largo porque heredó ese rasgo de sus progenitores.",
      ],
      answer: 0,
      explanation: "Explica el rasgo por un fin («con el propósito de»). Las otras dos apelan a causas anteriores (variación, reproducción, herencia).",
      hints: ["Buscá «para…» o «con el propósito de…».", "Teleológico = explicar por la meta.", "Una explicación causal mira hacia atrás, a los antecedentes."],
      errors: { 1: ["conceptual", "Esa explica por causas antecedentes (variación y reproducción): es la estrategia de Darwin."], 2: ["conceptual", "Apela a la herencia, una causa anterior; no a un fin."] },
    }),
    explain(
      "Las posiciones",
      "• **Creacionismo**: las especies fueron creadas según un plan; la adaptación se explica por **diseño**.\n• **Fijismo**: las especies **no cambian**. (Linneo clasificó especies por propiedades **esenciales**.)\n• **Lamarck**: las especies **cambian**. El **uso y desuso** desarrolla o atrofia órganos, y esos **caracteres adquiridos se heredan**.\n• **Lyell**: **gradualismo** y **actualismo**: las causas de hoy, actuando en tiempos enormes. Opuesto al **catastrofismo** de Cuvier.\n• **Malthus**: la población crece más que los alimentos → **lucha por la existencia**.",
      { tag: "matematico" },
    ),
    board(
      "Qué tomó Darwin de cada uno",
      [
        { expr: "Lamarck → la idea de evolución", note: "pero rechaza la herencia de lo adquirido" },
        { expr: "Lyell → tiempo profundo y cambio gradual", note: "hay tiempo suficiente para cambios lentos" },
        { expr: "Malthus → competencia por recursos escasos", note: "no todos sobreviven ni se reproducen" },
        { expr: "Criadores → selección artificial", note: "evidencia de herencia y variación, y la analogía que da nombre a la «selección natural»" },
        { expr: "Galápagos → pinzones distintos en islas distintas", note: "una especie colonizadora diversificada" },
      ],
      "Darwin integró piezas de fuentes muy distintas:",
    ),
    example(
      "Reconocer la influencia",
      "«Para explicar cómo se formó un cañón basta con suponer que el río erosionó la roca, como lo hace hoy, durante millones de años.» ¿De quién es la idea?",
      ["Habla de causas que operan hoy (erosión): actualismo.", "Actuando lentamente durante muchísimo tiempo: gradualismo.", "No apela a catástrofes (Cuvier) ni a seres vivos (Lamarck, Malthus)."],
      "Es una idea de Lyell.",
    ),
    practice("Ejercicio guiado", "ipc-antecedentes-darwin", 1, 3, true),
    explain(
      "Error típico: Lamarck y Darwin",
      "Lamarck y Darwin **coinciden** en que hay evolución y en que hace falta la herencia. **Difieren** en el origen de la variación.\n\nPara Lamarck, el rasgo aparece **porque el organismo lo necesita y lo usa**. Para Darwin, la variación **no está dirigida**: aparece primero, y el ambiente después «filtra».\n\nSi leés «de tanto usar… lo adquirieron y lo heredaron», es Lamarck.",
      { tag: "intuitivo" },
    ),
    practice("Tu turno", "ipc-antecedentes-darwin", 3, 8),
    practice("Desafío", "ipc-antecedentes-darwin", 5, 13),
    summary([
      "Explicación teleológica: por un fin. Darwin la reemplaza por causas antecedentes.",
      "Creacionismo: diseño. Fijismo: las especies no cambian.",
      "Lamarck: uso y desuso + herencia de caracteres adquiridos.",
      "Lyell: gradualismo y actualismo (vs. catastrofismo de Cuvier). Malthus: lucha por la existencia.",
      "Darwin toma de Lamarck la evolución, no el mecanismo.",
    ]),
  ],
  tutor: {
    normal: "Antes de Darwin, la adaptación se explicaba por diseño (creacionismo) sobre especies inmutables (fijismo). Lamarck propuso que las especies cambian por uso y desuso y herencia de caracteres adquiridos. Darwin integró la idea de evolución con el gradualismo de Lyell, la presión poblacional de Malthus y la evidencia de la selección artificial.",
    simple: "Antes se pensaba que cada especie había sido creada tal como es. Lamarck dijo que cambian porque los animales usan o dejan de usar partes del cuerpo y eso se hereda. Darwin aceptó que cambian, pero explicó el cambio de otra manera.",
    nino: "Para Lamarck, un levantador de pesas tendría hijos musculosos por haber entrenado. Para Darwin, no: los hijos heredan lo que traían los padres de nacimiento, no lo que ganaron en el gimnasio.",
    ejemplo: "Lamarck: «la jirafa estiró el cuello y se lo pasó a sus crías». Creacionismo: «la jirafa fue creada con cuello largo para comer hojas altas».",
    fromZero: "Los seres vivos son muy variados y parecen hechos a medida de su ambiente. Durante siglos se explicó eso diciendo que un creador los diseñó así y que no cambian. Después aparecieron ideas de cambio: Lamarck pensó que el esfuerzo de cada organismo lo transformaba. Geólogos como Lyell mostraron que la Tierra es antiquísima y cambia lento. Malthus mostró que nacen más individuos de los que pueden sobrevivir. Con esas piezas trabajó Darwin.",
    why: "Para entender una revolución científica hay que ver qué reemplazó. Además, reconocer el estilo de cada explicación (diseño, uso y herencia, selección) es exactamente lo que piden los ítems del parcial.",
    origin: "La teoría de Darwin no surgió de la nada: combina la idea de evolución, una escala temporal enorme (de la geología), un mecanismo de competencia (de la demografía) y una analogía (la selección artificial de los criadores).",
    board: [
      { expr: "Creacionismo: diseño + especies fijas" },
      { expr: "Lamarck: necesidad → uso → rasgo adquirido → herencia" },
      { expr: "Darwin: variación → competencia → selección → herencia" },
    ],
  },
};

export const ipcSeleccionNatural: Lesson = {
  id: "l-ipc-seleccion-natural",
  title: "Darwin y la selección natural",
  subtitle: "Variación, herencia, lucha por la existencia y ancestro común",
  subjectId: S,
  topicIds: ["t-ipc-seleccion-natural"],
  estimatedMinutes: 11,
  prerequisites: ["t-ipc-pre-darwin"],
  cards: [
    intro(
      "Adaptación sin diseño",
      "Vas a reconstruir la teoría de la selección natural, distinguirla de las explicaciones lamarckianas, creacionistas y de «puro azar», y conocer su actualidad.",
      "Es el núcleo evaluable de la Unidad 2: el parcial pide elegir la explicación darwiniana de un rasgo y justificar verdaderos o falsos sobre variación y herencia.",
    ),
    explain(
      "Un filtro, no un diseñador",
      "Imaginá un colador que, generación tras generación, deja pasar un poco más a quienes mejor se las arreglan en cierto ambiente. Nadie elige: el colador es ciego.\n\nSi además los hijos se parecen a los padres, con el tiempo la población cambia. Eso es la **selección natural**: un proceso **pasivo**, sin meta ni dirección.",
      { tag: "intuitivo" },
    ),
    quiz("Chequeo rápido", {
      id: "q-ipc-sel-1",
      subjectId: S,
      topicId: "t-ipc-seleccion-natural",
      prompt: "Según Darwin, que la variación sea **aleatoria** significa que…",
      options: ["no está dirigida por las necesidades que impone el ambiente.", "no tiene ninguna causa.", "todo en la evolución es cuestión de suerte.", "los rasgos nuevos siempre son perjudiciales."],
      answer: 0,
      explanation: "«Aleatoria» quiere decir no dirigida: un rasgo nuevo no aparece porque haga falta, y puede ser beneficioso, neutro o perjudicial. Pero la selección no es azarosa.",
      hints: ["¿Aleatorio es lo mismo que sin causa?", "Pensá en Lamarck: para él la variación SÍ respondía a la necesidad.", "Para Darwin el rasgo aparece primero; después el ambiente filtra."],
      errors: { 1: ["conceptual", "No: «aleatoria» no significa sin causa, sino no dirigida por las necesidades del organismo."], 2: ["conceptual", "La variación es aleatoria, pero la selección no: favorece sistemáticamente a los más aptos en un ambiente."], 3: ["conceptual", "Un rasgo nuevo puede ser beneficioso, neutro o perjudicial."] },
    }),
    explain(
      "Los ingredientes",
      "1. **Sobreproducción**: nacen más individuos de los que pueden sobrevivir (Malthus) → **lucha por la existencia**.\n2. **Variación**: en cada generación aparecen rasgos nuevos, **no dirigidos**.\n3. **Herencia**: se heredan **muchos** rasgos, útiles o no; la descendencia **no es idéntica**.\n4. **Aptitud**: cuánto un rasgo aumenta la probabilidad de sobrevivir y dejar descendencia. Es **relativa al ambiente** y **comparativa**.\n5. **Resultado**: aumenta la proporción de los más aptos. Las especies descienden de **ancestros comunes**.",
      { tag: "matematico" },
    ),
    board(
      "El argumento de Darwin, renglón por renglón",
      [
        { expr: "P1: Nacen más individuos de los que pueden sobrevivir.", note: "lucha por la existencia" },
        { expr: "P2: Los individuos varían, y algunas variaciones dan ventaja en un ambiente.", note: "variación + aptitud" },
        { expr: "P3: Muchos rasgos se heredan.", note: "herencia" },
        { expr: "C1: Los más aptos dejan, en promedio, más descendencia.", note: "de P1 y P2" },
        { expr: "C2: Generación tras generación aumenta la proporción del rasgo ventajoso.", note: "de C1 y P3" },
        { expr: "Explica la adaptación sin finalidad ni diseño", note: "reemplaza la teleología por causas antecedentes" },
      ],
      "Podemos leer la teoría como un argumento (¡Unidad 1!):",
    ),
    example(
      "Elegir la explicación darwiniana",
      "Las liebres árticas tienen pelaje blanco. ¿Cómo lo explica Darwin?",
      ["Entre sus ancestros había variación en el color del pelaje.", "En la nieve, las de pelaje más claro eran menos detectadas por los depredadores.", "Sobrevivían más y dejaban más crías, que heredaban el pelaje claro.", "La proporción de liebres claras aumentó generación tras generación."],
      "Variación previa + ventaja en ese ambiente + más descendencia + herencia.",
    ),
    practice("Ejercicio guiado", "ipc-explicacion-evolutiva", 1, 2, true),
    explain(
      "Cómo descartar las otras",
      "• **Lamarckiana**: «de tanto usar/estirar… lo adquirieron y lo heredaron».\n• **Creacionista**: «fueron creados con… para…», «armonía», «diseño».\n• **Azar puro**: «sin relación con el ambiente». Falla: la variación es aleatoria, la **selección no**.\n• **Progresista**: «la evolución va hacia lo más perfecto». Falla: la selección es **ciega**, sin dirección.\n\nTampoco: «se heredan solo los rasgos útiles» ni «los rasgos nuevos siempre mejoran la aptitud».",
      { tag: "intuitivo" },
    ),
    practice("Tu turno", "ipc-darwin-vf", 2, 6),
    practice("Verdadero o falso con justificación", "ipc-darwin-vf", 4, 11),
    practice("Desafío", "ipc-explicacion-evolutiva", 5, 17),
    summary([
      "Ingredientes: sobreproducción, variación no dirigida, herencia, aptitud relativa al ambiente.",
      "La variación es aleatoria (no dirigida); la selección no es azarosa.",
      "La selección es ciega: no tiene meta ni dirección de progreso.",
      "Teoría sintética: Darwin + genética; las mutaciones explican la variación.",
      "Darwin y Lamarck coinciden en la evolución y la herencia; difieren en el origen de la variación.",
    ]),
  ],
  tutor: {
    normal: "La teoría de la selección natural explica el origen y la adaptación de las especies por variación no dirigida, herencia y diferencias en supervivencia y reproducción en un ambiente con recursos limitados. La aptitud es relativa al ambiente y comparativa. La teoría sintética integró esta explicación con la genética: las mutaciones son la fuente de la variación.",
    simple: "Los individuos nacen distintos. En cada ambiente, a algunos les va mejor y tienen más crías, que heredan sus rasgos. Con muchas generaciones, la especie cambia. Nadie lo planea.",
    nino: "Imaginá un juego de escondidas en un pasto verde con chicos vestidos de colores. Los de verde casi nunca son encontrados. Si cada ronda los que no fueron encontrados «tienen hijos» vestidos como ellos, después de muchas rondas casi todos van a estar de verde.",
    ejemplo: "Bacterias y antibióticos: en una población, algunas bacterias ya eran un poco más resistentes. El antibiótico elimina a las demás; las resistentes se reproducen, y la población se vuelve resistente.",
    fromZero: "Todo ser vivo tiene crías parecidas, pero no iguales, a sus padres. Nacen más de los que pueden sobrevivir con los recursos que hay. Los que tienen rasgos que los ayudan en su ambiente tienen más chances de sobrevivir y reproducirse, y pasan esos rasgos. Repetido durante muchísimo tiempo, eso cambia a las especies y las adapta, sin que nadie lo dirija.",
    why: "La teoría de Darwin muestra cómo la ciencia puede explicar lo que parecía diseño con causas naturales. Además, cambió la imagen del ser humano y de la naturaleza: ya no hay especies fijas ni un progreso garantizado.",
    origin: "Darwin combinó la presión poblacional de Malthus, la variación y la herencia que mostraban los criadores, y el tiempo profundo de Lyell. La analogía con la selección artificial le dio el nombre: la naturaleza «selecciona» sin elegir, por diferencias de supervivencia y reproducción.",
    board: [
      { expr: "Variación no dirigida", note: "aparecen rasgos distintos" },
      { expr: "Ventaja en un ambiente", note: "aptitud relativa" },
      { expr: "Más descendencia", note: "lucha por la existencia" },
      { expr: "Herencia", note: "las crías se parecen a los padres" },
      { expr: "Cambio gradual de la población", note: "sin finalidad ni diseño" },
    ],
  },
};

const U2_LESSONS: Lesson[] = [ipcPreDarwin, ipcSeleccionNatural];

// @@U3@@


export const ipcLessons: Lesson[] = [...U1_LESSONS, ...U2_LESSONS];
