import type { Lesson } from "@/engine/types";
import { example, explain, intro, practice, quiz, summary } from "./helpers";

export const factorizacion: Lesson = {
  id: "l-factorizacion",
  title: "Factorización",
  subtitle: "Escribir una suma como producto",
  subjectId: "preparacion",
  topicIds: ["t-factorizacion"],
  estimatedMinutes: 10,
  prerequisites: ["t-expresiones", "t-potencias"],
  cards: [
    intro("Factorizar", "Pasar de una suma a un producto: factor común, diferencia de cuadrados y trinomios.", "Factorizar es la herramienta para simplificar fracciones algebraicas, resolver cuadráticas y destrabar límites del tipo 0/0 en Análisis Matemático A."),
    explain(
      "La idea",
      "Factorizar es lo contrario de distribuir. Distribuir: $3(x + 2) = 3x + 6$. Factorizar: $3x + 6 = 3(x + 2)$.\n\nEs como escribir $12 = 3 · 4$: el mismo número, mostrado como multiplicación. Un producto es más fácil de simplificar y de igualar a cero.",
      { tag: "intuitivo" },
    ),
    quiz("Pregunta rápida", {
      id: "q-fact-1", subjectId: "preparacion", topicId: "t-factorizacion",
      prompt: "¿Cuál es la forma factorizada de $5x + 10$?",
      options: ["$5(x + 2)$", "$5(x + 10)$", "$x(5 + 10)$"],
      answer: 0,
      explanation: "5 divide a los dos términos: 5x ÷ 5 = x y 10 ÷ 5 = 2. Verificación: 5(x + 2) = 5x + 10.",
      hints: ["¿Qué número divide a 5x y a 10?", "Es el 5.", "Dividí cada término por 5."],
      errors: { 1: ["factorizacion", "Si distribuís 5(x + 10) da 5x + 50. Cada término se DIVIDE por el factor común."] },
    }),
    explain(
      "Diferencia de cuadrados",
      "Cuando hay un cuadrado menos otro cuadrado:\n\n$a^2 − b^2 = (a − b)(a + b)$\n\nPor ejemplo $x^2 − 9 = (x − 3)(x + 3)$. Si distribuís, los términos $−3x$ y $+3x$ se cancelan.\n\nError clásico: escribir $(x − 3)^2$, que en realidad es $x^2 − 6x + 9$.",
      { tag: "matematico" },
    ),
    practice("Ejercicio guiado", "factorizar", 2, 21, true),
    explain(
      "Trinomios: suma y producto",
      "Para $x^2 + 5x + 6$ buscá dos números que **multiplicados** den 6 y **sumados** den 5: son 2 y 3.\n\n$x^2 + 5x + 6 = (x + 2)(x + 3)$\n\nCon signos: $x^2 − x − 6$ → producto −6, suma −1 → los números son −3 y 2 → $(x − 3)(x + 2)$.",
      { tag: "matematico" },
    ),
    example("Ejemplo resuelto", "Factorizá $x^2 + 2x − 15$", ["Producto −15 y suma 2", "Probamos pares: (5, −3) → 5·(−3) = −15 y 5 + (−3) = 2 ✓", "$x^2 + 2x − 15 = (x + 5)(x − 3)$", "Verifico: $x^2 − 3x + 5x − 15$ ✓"], "(x + 5)(x − 3)"),
    practice("Tu turno", "factorizar", 4, 8),
    practice("Mini desafío", "factorizar", 6, 13),
    summary(["Factorizar = escribir como producto (la distributiva al revés).", "Factor común: dividí cada término por lo que comparten.", "a² − b² = (a − b)(a + b).", "Trinomio x² + Sx + P: dos números con suma S y producto P.", "Siempre se puede verificar distribuyendo."]),
  ],
  tutor: {
    normal: "Factorizar una expresión es escribirla como producto de factores más simples. Los casos básicos son factor común, diferencia de cuadrados y trinomio cuadrado.",
    simple: "Es deshacer la distributiva. Si tenés 3x + 6, preguntate qué número está «metido» en los dos términos: el 3. Entonces 3x + 6 = 3(x + 2).",
    nino: "Tenés 12 caramelos y querés armar bolsitas iguales: podés hacer 3 bolsitas de 4. Factorizar es encontrar cómo armar esas bolsitas con una expresión.",
    ejemplo: "x² − 25 = (x − 5)(x + 5). x² + 7x + 10 = (x + 2)(x + 5), porque 2·5 = 10 y 2 + 5 = 7.",
  },
};

export const cuadratica: Lesson = {
  id: "l-cuadratica",
  title: "Ecuaciones cuadráticas",
  subtitle: "Cuando la x está al cuadrado",
  subjectId: "preparacion",
  topicIds: ["t-cuadratica"],
  estimatedMinutes: 10,
  prerequisites: ["t-factorizacion", "t-ecuaciones"],
  cards: [
    intro("Cuadráticas", "Resolver ecuaciones como x² − 5x + 6 = 0 factorizando o con la fórmula resolvente.", "Aparecen en tiro vertical (¿cuándo toca el suelo?), en áreas, en optimización y en casi todos los ejercicios de funciones del CBC."),
    explain(
      "Un producto que da cero",
      "Si $A · B = 0$, entonces $A = 0$ o $B = 0$ (no hay otra forma de que un producto dé cero).\n\nPor eso, si $(x − 2)(x − 3) = 0$: o bien $x − 2 = 0$, o bien $x − 3 = 0$. Las soluciones son $x = 2$ y $x = 3$.",
      { tag: "intuitivo" },
    ),
    quiz("Pregunta rápida", {
      id: "q-cuad-1", subjectId: "preparacion", topicId: "t-cuadratica",
      prompt: "¿Cuáles son las soluciones de $(x + 4)(x − 1) = 0$?",
      options: ["$x = −4$ y $x = 1$", "$x = 4$ y $x = −1$", "Solo $x = 1$"],
      answer: 0,
      explanation: "x + 4 = 0 → x = −4; x − 1 = 0 → x = 1.",
      hints: ["Igualá cada factor a cero.", "x + 4 = 0 → x = ?", "Al despejar, el número cambia de signo."],
      errors: { 1: ["signos", "De x + 4 = 0 sale x = −4: el 4 pasa restando."] },
    }),
    explain(
      "La fórmula resolvente",
      "Para $ax^2 + bx + c = 0$ siempre funciona:\n\n$x = \\frac{−b ± √(b^2 − 4ac)}{2a}$\n\nEl número $Δ = b^2 − 4ac$ (discriminante) dice cuántas soluciones hay: positivo → dos; cero → una; negativo → ninguna real.",
      { tag: "matematico" },
    ),
    example("Ejemplo resuelto", "Resolvé $x^2 − 5x + 6 = 0$", ["Factorizo: producto 6, suma −5 → −2 y −3", "$(x − 2)(x − 3) = 0$", "$x = 2$ o $x = 3$", "Con la fórmula: $Δ = 25 − 24 = 1$, $x = (5 ± 1)/2$ → 3 y 2 ✓"], "x = 2 y x = 3"),
    practice("Ejercicio guiado", "ecuacion-cuadratica", 2, 4, true),
    practice("Tu turno", "ecuacion-cuadratica", 4, 9),
    practice("Mini desafío", "ecuacion-cuadratica", 6, 12),
    summary(["Si A·B = 0, entonces A = 0 o B = 0.", "Factorizar y igualar cada factor a cero.", "Fórmula: x = (−b ± √(b² − 4ac)) / 2a.", "Δ > 0: dos soluciones; Δ = 0: una; Δ < 0: ninguna real."]),
  ],
  tutor: {
    normal: "Una ecuación cuadrática ax² + bx + c = 0 se resuelve factorizando y usando que un producto es cero solo si algún factor es cero, o con la fórmula resolvente.",
    simple: "Convertí la ecuación en una multiplicación igualada a cero, y después pensá: ¿qué valor de x hace cero cada paréntesis?",
    nino: "Si multiplicás dos números y te da 0, uno de los dos tiene que ser 0. Con eso se encuentran las soluciones.",
    ejemplo: "x² − 9 = 0 → (x − 3)(x + 3) = 0 → x = 3 o x = −3.",
    visual: { type: "plot", mode: "free", initial: "x^2 - 5x + 6" },
    visualText: "Las soluciones son los puntos donde la parábola corta al eje x.",
  },
};

export const pitagorasLesson: Lesson = {
  id: "l-pitagoras",
  title: "Pitágoras y distancias",
  subtitle: "El teorema más usado de la geometría",
  subjectId: "preparacion",
  topicIds: ["t-pitagoras"],
  estimatedMinutes: 8,
  prerequisites: ["t-potencias"],
  cards: [
    intro("Pitágoras", "Calcular lados de triángulos rectángulos y distancias entre puntos.", "Es la base del módulo de un vector, de la distancia en el plano, de la trigonometría y de la física en dos dimensiones."),
    explain(
      "El teorema",
      "En un triángulo **rectángulo** (con un ángulo de 90°), el lado más largo es la **hipotenusa** $h$ y los otros dos son los **catetos** $a$ y $b$:\n\n$h^2 = a^2 + b^2$\n\nCon catetos 3 y 4: $h^2 = 9 + 16 = 25$, así que $h = 5$. Mové la punta y mirá cómo se cumple:",
      { tag: "matematico", widget: { type: "vector", x: 3, y: 4 } },
    ),
    quiz("Pregunta rápida", {
      id: "q-pit-1", subjectId: "preparacion", topicId: "t-pitagoras",
      prompt: "Una escalera de 5 m se apoya en una pared con su base a 3 m. ¿A qué altura llega?",
      options: ["4 m", "2 m", "8 m"],
      answer: 0,
      explanation: "La escalera es la hipotenusa: altura² = 5² − 3² = 16, altura = 4 m.",
      hints: ["La escalera es la hipotenusa.", "altura² = 5² − 3².", "25 − 9 = 16."],
      errors: { 1: ["formula", "Restaste las longitudes sin elevar al cuadrado. Pitágoras trabaja con cuadrados."], 2: ["despeje", "Sumaste. Si buscás un cateto, se resta: b² = h² − a²."] },
    }),
    practice("Ejercicio guiado", "pitagoras", 1, 3, true),
    explain(
      "Distancia entre dos puntos",
      "Entre $(x_1, y_1)$ y $(x_2, y_2)$ se forma un triángulo rectángulo con catetos $Δx$ y $Δy$:\n\n$d = √((x_2 − x_1)^2 + (y_2 − y_1)^2)$\n\nEs Pitágoras con coordenadas.",
      { tag: "matematico" },
    ),
    practice("Tu turno", "pitagoras", 3, 6),
    practice("Mini desafío", "pitagoras", 5, 11),
    summary(["h² = a² + b² (solo en triángulos rectángulos).", "Para un cateto: b² = h² − a².", "Distancia: d = √(Δx² + Δy²)."]),
  ],
  tutor: {
    normal: "En todo triángulo rectángulo, el cuadrado de la hipotenusa es igual a la suma de los cuadrados de los catetos.",
    simple: "Si conocés dos lados de un triángulo con ángulo recto, podés calcular el tercero: elevás al cuadrado, sumás (o restás) y sacás la raíz.",
    nino: "Si caminás 3 cuadras al este y 4 al norte, en línea recta estás a 5 cuadras del inicio.",
    ejemplo: "Catetos 6 y 8: h = √(36 + 64) = √100 = 10.",
    visual: { type: "vector", x: 6, y: 8 },
  },
};

export const trigonometriaLesson: Lesson = {
  id: "l-trigonometria",
  title: "Trigonometría básica",
  subtitle: "Seno, coseno y tangente",
  subjectId: "preparacion",
  topicIds: ["t-trigonometria"],
  estimatedMinutes: 12,
  prerequisites: ["t-pitagoras", "t-fracciones"],
  cards: [
    intro("Trigonometría", "Qué son el seno, el coseno y la tangente, cómo calcular lados con ellos y qué es un radián.", "Física la usa en cada problema con ángulos: tiro oblicuo, planos inclinados, componentes de fuerzas. Y Análisis Matemático A estudia las funciones trigonométricas."),
    explain(
      "Razones de un ángulo",
      "En un triángulo rectángulo, mirando desde un ángulo $α$:\n\n• **seno**: $sen α$ = opuesto / hipotenusa\n• **coseno**: $cos α$ = adyacente / hipotenusa\n• **tangente**: $tan α$ = opuesto / adyacente\n\nMové el ángulo y mirá cómo cambian:",
      { tag: "matematico", widget: { type: "trig", angle: 30, hyp: 10 } },
    ),
    quiz("Pregunta rápida", {
      id: "q-trig-1", subjectId: "preparacion", topicId: "t-trigonometria",
      prompt: "Si la hipotenusa mide 10 y $sen α = 0,5$, ¿cuánto mide el cateto opuesto a α?",
      options: ["5", "20", "0,05"],
      answer: 0,
      explanation: "sen α = opuesto / hipotenusa → opuesto = 10 · 0,5 = 5.",
      hints: ["Escribí la definición del seno.", "0,5 = opuesto / 10.", "Despejá multiplicando por 10."],
      errors: { 1: ["despeje", "Dividiste 10 por 0,5. Despejá: opuesto = hipotenusa · sen α."] },
    }),
    explain(
      "Para qué sirve",
      "Una rampa de 10 m forma 30° con el piso. ¿Qué altura sube?\n\nAltura = opuesto al ángulo → $10 · sen 30° = 10 · 0,5 = 5$ m.\n\nEsto mismo se hace en Física para descomponer una velocidad o una fuerza en sus componentes.",
      { tag: "cotidiano" },
    ),
    practice("Ejercicio guiado", "trigonometria", 2, 5, true),
    explain(
      "Grados y radianes",
      "Los ángulos también se miden en **radianes**: una vuelta completa son $2π$ rad, así que $180° = π$ rad.\n\nPara pasar de grados a radianes se multiplica por $π/180$: $90° = π/2$, $60° = π/3$.\n\nCuidado: la calculadora tiene que estar en el modo correcto (DEG para grados, RAD para radianes).",
      { tag: "matematico" },
    ),
    practice("Tu turno", "trigonometria", 3, 7),
    practice("Tu turno", "trigonometria", 4, 14),
    practice("Mini desafío", "trigonometria", 6, 3),
    summary(["sen = opuesto/hipotenusa; cos = adyacente/hipotenusa; tan = opuesto/adyacente.", "opuesto = h·sen α; adyacente = h·cos α.", "180° = π rad.", "Calculadora en DEG o RAD según el problema."]),
  ],
  tutor: {
    normal: "Las razones trigonométricas relacionan un ángulo agudo de un triángulo rectángulo con los cocientes entre sus lados.",
    simple: "El seno te dice qué fracción de la hipotenusa «sube» (cateto opuesto); el coseno, qué fracción «avanza» (cateto adyacente).",
    nino: "Si subís por una rampa de 10 metros muy inclinada, subís mucha altura; si es poco inclinada, subís poco. El seno del ángulo te dice exactamente cuánto.",
    ejemplo: "Hipotenusa 8 y ángulo 60°: adyacente = 8·cos 60° = 8·0,5 = 4.",
    visual: { type: "trig", angle: 45, hyp: 8 },
    visualText: "Mové el ángulo: el seno es la altura relativa y el coseno el avance relativo.",
  },
};

export const limitesLesson: Lesson = {
  id: "l-limites",
  title: "La idea de límite",
  subtitle: "Acercarse sin llegar",
  subjectId: "am-a",
  topicIds: ["t-limites"],
  estimatedMinutes: 12,
  prerequisites: ["t-funciones", "t-factorizacion"],
  cards: [
    intro("Límites", "Qué significa que una función «se acerque» a un valor, cómo calcularlo reemplazando, y qué hacer cuando aparece 0/0.", "Los límites son la base de todo Análisis Matemático A: con ellos se definen la continuidad, la derivada y la integral."),
    explain(
      "Acercarse",
      "$lim_{x→2} f(x) = L$ se lee: «cuando x se acerca a 2, f(x) se acerca a L».\n\nNo importa qué pasa **exactamente** en $x = 2$; importa hacia dónde van los valores cerca de 2.",
      { tag: "intuitivo" },
    ),
    explain(
      "Mirá la tabla",
      "La función $f(x) = \\frac{x^2 − 4}{x − 2}$ no existe en $x = 2$ (sería 0/0). Pero cerca de 2 los valores se acercan a 4. El gráfico es una recta con un hueco:",
      { tag: "matematico", widget: { type: "plot", mode: "free", initial: "(x^2 - 4)/(x - 2)" } },
    ),
    quiz("Pregunta rápida", {
      id: "q-lim-1", subjectId: "am-a", topicId: "t-limites",
      prompt: "Si $f(1,9) = 3,9$, $f(1,99) = 3,99$ y $f(2,01) = 4,01$, ¿a qué se acerca $f(x)$ cuando $x → 2$?",
      options: ["4", "2", "No se puede saber"],
      answer: 0,
      explanation: "Por los dos lados los valores se acercan a 4: el límite es 4.",
      hints: ["Mirá hacia dónde van los valores de f.", "3,9 → 3,99 → … y 4,01 → …", "Por izquierda y por derecha se acercan al mismo número."],
      errors: { 1: ["limites", "2 es hacia donde va x. El límite es hacia dónde van los valores de f(x)."] },
    }),
    explain(
      "Cómo calcularlo",
      "1. **Reemplazá.** Si da un número, ese es el límite: $lim_{x→3} (x^2 + 1) = 10$.\n2. Si da **0/0**, es una **indeterminación**: no vale 0 ni 1. Numerador y denominador comparten un factor.\n3. **Factorizá, simplificá y reemplazá** de nuevo:\n\n$\\frac{x^2 − 4}{x − 2} = \\frac{(x − 2)(x + 2)}{x − 2} = x + 2$ → con $x = 2$ da **4**.",
      { tag: "matematico" },
    ),
    practice("Ejercicio guiado", "limite", 1, 4, true),
    practice("Tu turno", "limite", 3, 9),
    practice("Tu turno", "limite", 4, 15),
    practice("Mini desafío", "limite", 5, 2),
    summary(["El límite mira hacia dónde van los valores, no el valor exacto.", "Primero, reemplazar.", "0/0 es una indeterminación: factorizar, simplificar y reemplazar.", "Si te trabás factorizando, repasá factorización: es la herramienta clave."]),
  ],
  tutor: {
    normal: "El límite de f(x) cuando x tiende a a es el valor al que se aproximan las imágenes de f para x suficientemente cercanos a a, sin importar el valor (o la ausencia de valor) en a.",
    simple: "Preguntá: si me acerco muchísimo a ese x, ¿a qué número se acerca la función? Primero probá reemplazar; si da 0/0, simplificá.",
    nino: "Si caminás hacia una pared dando pasos cada vez más cortos, nunca la tocás, pero está clarísimo hacia dónde vas. El límite es esa pared.",
    ejemplo: "lim x→3 de (x² − 9)/(x − 3): reemplazar da 0/0; (x − 3)(x + 3)/(x − 3) = x + 3 → 6.",
    visual: { type: "plot", mode: "free", initial: "(x^2 - 9)/(x - 3)" },
  },
};

export const derivadasLesson: Lesson = {
  id: "l-derivadas",
  title: "La derivada",
  subtitle: "Pendiente y tasa de cambio",
  subjectId: "am-a",
  topicIds: ["t-derivadas"],
  estimatedMinutes: 12,
  prerequisites: ["t-recta", "t-potencias", "t-limites"],
  cards: [
    intro("Derivadas", "Qué significa una derivada (la pendiente de la tangente, la velocidad instantánea) y la regla de la potencia.", "Con derivadas se calculan velocidades y aceleraciones, se encuentran máximos y mínimos y se optimiza: es la herramienta central de Análisis Matemático A."),
    explain(
      "El velocímetro",
      "Si un auto recorre 100 km en 2 horas, su velocidad **media** fue 50 km/h. Pero el velocímetro muestra la velocidad **en cada instante**.\n\nLa derivada es eso: cuánto cambia una función **en un instante**, no en promedio.",
      { tag: "cotidiano" },
    ),
    explain(
      "Pendiente de la tangente",
      "En un gráfico, la derivada en un punto es la **pendiente de la recta tangente** (la recta que «roza» la curva ahí). Mové el punto:",
      { tag: "intuitivo", widget: { type: "tangent", initial: "x^2" } },
    ),
    quiz("Pregunta rápida", {
      id: "q-der-1", subjectId: "am-a", topicId: "t-derivadas",
      prompt: "En el punto más bajo de una parábola como $x^2$, ¿cuánto vale la pendiente de la tangente?",
      options: ["0", "1", "No existe"],
      answer: 0,
      explanation: "En el mínimo la tangente es horizontal: pendiente 0. Por eso los máximos y mínimos se buscan donde la derivada vale 0.",
      hints: ["Imaginá la recta que toca la parábola justo en el fondo.", "¿Esa recta sube, baja o es horizontal?", "Una recta horizontal tiene pendiente 0."],
      errors: { 2: ["derivacion", "La parábola es suave en el mínimo: la tangente existe y es horizontal."] },
    }),
    explain(
      "Regla de la potencia",
      "No hace falta dibujar cada vez. Para potencias de x:\n\n$(x^n)′ = n · x^{n−1}$\n\nEl exponente baja multiplicando y se le resta 1. Ejemplos: $(x^2)′ = 2x$, $(x^3)′ = 3x^2$, $(5x^4)′ = 20x^3$.\n\nUna constante sumando desaparece: $(x^2 + 7)′ = 2x$. Y $(kx)′ = k$.",
      { tag: "matematico" },
    ),
    example("Ejemplo resuelto", "Derivá $f(x) = 3x^4 − 2x + 5$", ["$(3x^4)′ = 3 · 4 · x^3 = 12x^3$", "$(−2x)′ = −2$", "$(5)′ = 0$", "$f′(x) = 12x^3 − 2$"], "f′(x) = 12x³ − 2"),
    practice("Ejercicio guiado", "derivada-potencia", 2, 6, true),
    practice("Tu turno", "derivada-potencia", 3, 10),
    practice("Mini desafío", "derivada-potencia", 5, 3),
    summary(["La derivada es la tasa de cambio instantánea.", "Geométricamente: la pendiente de la recta tangente.", "(xⁿ)′ = n·xⁿ⁻¹; (kx)′ = k; (constante)′ = 0.", "Donde la derivada vale 0, la tangente es horizontal (candidatos a máximo o mínimo)."]),
  ],
  tutor: {
    normal: "La derivada de f en a es el límite del cociente incremental [f(a + h) − f(a)]/h cuando h → 0: la pendiente de la recta tangente al gráfico en ese punto.",
    simple: "La derivada te dice qué tan rápido está cambiando algo justo ahora. Si es grande y positiva, la función sube rápido; si es 0, está «quieta» por un instante.",
    nino: "Es el velocímetro de la función: no te dice dónde está, te dice qué tan rápido va.",
    ejemplo: "f(x) = x²: f′(x) = 2x. En x = 3 la pendiente es 6: por cada paso chiquito a la derecha, sube unas 6 veces ese paso.",
    visual: { type: "tangent", initial: "x^2" },
    visualText: "Mové el punto y mirá cómo cambia la pendiente de la tangente.",
  },
};

export const precalculoLessons = [factorizacion, cuadratica, pitagorasLesson, trigonometriaLesson, limitesLesson, derivadasLesson];
